// UI_TEXT — all interface strings translated by native language
// Add more languages here as needed

export interface UIStrings {
  appTagline: string;
  iSpeak: string;
  iWantToSpeak: string;
  placeholder: string;
  sayItButton: string;
  hearSlowly: string;
  naturalSpeed: string;
  playing: string;
  stop: string;
  sayThisIn: string;
  wordByWord: string;
  soundsLike: string;
  means: string;
  proTip: string;
  formalVersion: string;
  backToList: string;
  quickPhrases: string;
  customPhrasesNote: string;
  instant: string;
  generating: string;
  errorMessage: string;
  toneLabels: Record<string, { label: string; desc: string }>;
}

const UI_TEXT: Record<string, UIStrings> = {
  en: {
    appTagline: "Speak any phrase. No reading required.",
    iSpeak: "I speak",
    iWantToSpeak: "I want to speak",
    placeholder: "Type any phrase in English...",
    sayItButton: "SAY IT →",
    hearSlowly: "Hear it slowly",
    naturalSpeed: "Natural speed",
    playing: "Playing...",
    stop: "Stop",
    sayThisIn: "Say this in",
    wordByWord: "Word-by-Word Breakdown",
    soundsLike: "Sounds like",
    means: "Means:",
    proTip: "Pro Tip",
    formalVersion: "Formal / Polite Version",
    backToList: "← Back to phrase list",
    quickPhrases: "Quick Phrases — tap for instant breakdown",
    customPhrasesNote: "Custom phrases typed above are AI-generated on the fly",
    instant: "instant",
    generating: "Breaking it down for you...",
    errorMessage: "Something went wrong. Please try again.",
    toneLabels: {
      rising:  { label: "Rising",  desc: "Voice goes UP at the end" },
      falling: { label: "Falling", desc: "Voice goes DOWN" },
      flat:    { label: "Flat",    desc: "Keep voice LEVEL" },
      dipping: { label: "Dipping", desc: "Dips DOWN then back UP" },
      high:    { label: "High",    desc: "Start and stay HIGH" },
      low:     { label: "Low",     desc: "Start and stay LOW" },
      broken:  { label: "Broken",  desc: "Tight throat, creaky sound" },
    },
  },

  vi: {
    appTagline: "Nói bất kỳ câu nào. Không cần đọc.",
    iSpeak: "Tôi nói",
    iWantToSpeak: "Tôi muốn nói",
    placeholder: "Nhập bất kỳ câu nào bằng tiếng Việt...",
    sayItButton: "NÓI NÀO →",
    hearSlowly: "Nghe chậm",
    naturalSpeed: "Tốc độ bình thường",
    playing: "Đang phát...",
    stop: "Dừng",
    sayThisIn: "Nói câu này bằng",
    wordByWord: "Phân tích từng từ",
    soundsLike: "Nghe giống như",
    means: "Nghĩa:",
    proTip: "Mẹo hay",
    formalVersion: "Phiên bản trang trọng",
    backToList: "← Quay lại danh sách",
    quickPhrases: "Câu thông dụng — nhấn để xem ngay",
    customPhrasesNote: "Câu tự nhập sẽ được AI tạo ra",
    instant: "ngay",
    generating: "Đang phân tích cho bạn...",
    errorMessage: "Có lỗi xảy ra. Vui lòng thử lại.",
    toneLabels: {
      rising:  { label: "Lên",      desc: "Giọng đi LÊN cuối câu" },
      falling: { label: "Xuống",    desc: "Giọng đi XUỐNG" },
      flat:    { label: "Bằng",     desc: "Giữ giọng PHẲNG" },
      dipping: { label: "Xuống rồi lên", desc: "Giọng xuống rồi lên lại" },
      high:    { label: "Cao",      desc: "Bắt đầu và giữ CAO" },
      low:     { label: "Thấp",     desc: "Bắt đầu và giữ THẤP" },
      broken:  { label: "Gãy",      desc: "Cổ họng căng, giọng ngắt" },
    },
  },

  es: {
    appTagline: "Di cualquier frase. Sin necesidad de leer.",
    iSpeak: "Yo hablo",
    iWantToSpeak: "Quiero hablar",
    placeholder: "Escribe cualquier frase en español...",
    sayItButton: "¡DILO →",
    hearSlowly: "Escuchar despacio",
    naturalSpeed: "Velocidad natural",
    playing: "Reproduciendo...",
    stop: "Detener",
    sayThisIn: "Di esto en",
    wordByWord: "Desglose palabra por palabra",
    soundsLike: "Suena como",
    means: "Significa:",
    proTip: "Consejo",
    formalVersion: "Versión formal",
    backToList: "← Volver a la lista",
    quickPhrases: "Frases rápidas — toca para ver",
    customPhrasesNote: "Las frases personalizadas son generadas por IA",
    instant: "al instante",
    generating: "Analizando para ti...",
    errorMessage: "Algo salió mal. Por favor intenta de nuevo.",
    toneLabels: {
      rising:  { label: "Ascendente",  desc: "La voz SUBE al final" },
      falling: { label: "Descendente", desc: "La voz BAJA" },
      flat:    { label: "Plano",       desc: "Mantén la voz NIVELADA" },
      dipping: { label: "Baja y sube", desc: "Baja y luego SUBE" },
      high:    { label: "Alto",        desc: "Empieza y mantén ALTO" },
      low:     { label: "Bajo",        desc: "Empieza y mantén BAJO" },
      broken:  { label: "Cortado",     desc: "Garganta tensa, sonido cortado" },
    },
  },

  de: {
    appTagline: "Sag jeden Satz. Kein Lesen erforderlich.",
    iSpeak: "Ich spreche",
    iWantToSpeak: "Ich möchte sprechen",
    placeholder: "Gib einen Satz auf Deutsch ein...",
    sayItButton: "SAG ES →",
    hearSlowly: "Langsam anhören",
    naturalSpeed: "Normale Geschwindigkeit",
    playing: "Wird abgespielt...",
    stop: "Stopp",
    sayThisIn: "Sag das auf",
    wordByWord: "Wort-für-Wort-Aufschlüsselung",
    soundsLike: "Klingt wie",
    means: "Bedeutet:",
    proTip: "Tipp",
    formalVersion: "Formelle Version",
    backToList: "← Zurück zur Liste",
    quickPhrases: "Schnellphrasen — tippen für sofortige Analyse",
    customPhrasesNote: "Eigene Phrasen werden von KI generiert",
    instant: "sofort",
    generating: "Wird analysiert...",
    errorMessage: "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    toneLabels: {
      rising:  { label: "Steigend",   desc: "Stimme geht AM ENDE hoch" },
      falling: { label: "Fallend",    desc: "Stimme geht RUNTER" },
      flat:    { label: "Flach",      desc: "Stimme GLEICHMÄSSIG halten" },
      dipping: { label: "Tief-hoch",  desc: "Runter dann wieder hoch" },
      high:    { label: "Hoch",       desc: "Hoch beginnen und halten" },
      low:     { label: "Tief",       desc: "Tief beginnen und halten" },
      broken:  { label: "Gebrochen",  desc: "Kehle angespannt, Knacklaut" },
    },
  },

  nl: {
    appTagline: "Spreek elke zin uit. Geen lezen vereist.",
    iSpeak: "Ik spreek",
    iWantToSpeak: "Ik wil spreken",
    placeholder: "Typ een zin in het Nederlands...",
    sayItButton: "ZEG HET →",
    hearSlowly: "Langzaam beluisteren",
    naturalSpeed: "Normale snelheid",
    playing: "Wordt afgespeeld...",
    stop: "Stop",
    sayThisIn: "Zeg dit in het",
    wordByWord: "Woord-voor-woord uitleg",
    soundsLike: "Klinkt als",
    means: "Betekent:",
    proTip: "Tip",
    formalVersion: "Formele versie",
    backToList: "← Terug naar de lijst",
    quickPhrases: "Snelle zinnen — tik voor directe uitleg",
    customPhrasesNote: "Eigen zinnen worden door AI gegenereerd",
    instant: "direct",
    generating: "Wordt geanalyseerd...",
    errorMessage: "Er is iets misgegaan. Probeer opnieuw.",
    toneLabels: {
      rising:  { label: "Stijgend",  desc: "Stem gaat OMHOOG aan het einde" },
      falling: { label: "Dalend",    desc: "Stem gaat OMLAAG" },
      flat:    { label: "Vlak",      desc: "Stem GELIJK houden" },
      dipping: { label: "Dal-stijg", desc: "Omlaag dan weer omhoog" },
      high:    { label: "Hoog",      desc: "Begin en blijf HOOG" },
      low:     { label: "Laag",      desc: "Begin en blijf LAAG" },
      broken:  { label: "Gebroken",  desc: "Gespannen keel, krakend geluid" },
    },
  },

  fr: {
    appTagline: "Dites n'importe quelle phrase. Sans lecture.",
    iSpeak: "Je parle",
    iWantToSpeak: "Je veux parler",
    placeholder: "Tapez n'importe quelle phrase en français...",
    sayItButton: "DITES-LE →",
    hearSlowly: "Écouter lentement",
    naturalSpeed: "Vitesse naturelle",
    playing: "Lecture en cours...",
    stop: "Arrêter",
    sayThisIn: "Dites ceci en",
    wordByWord: "Décomposition mot par mot",
    soundsLike: "Ça ressemble à",
    means: "Signifie :",
    proTip: "Conseil",
    formalVersion: "Version formelle",
    backToList: "← Retour à la liste",
    quickPhrases: "Phrases rapides — appuyez pour voir",
    customPhrasesNote: "Les phrases personnalisées sont générées par l'IA",
    instant: "instantané",
    generating: "Analyse en cours...",
    errorMessage: "Une erreur s'est produite. Veuillez réessayer.",
    toneLabels: {
      rising:  { label: "Montant",    desc: "La voix MONTE à la fin" },
      falling: { label: "Descendant", desc: "La voix DESCEND" },
      flat:    { label: "Plat",       desc: "Garder la voix STABLE" },
      dipping: { label: "Bas-haut",   desc: "Descend puis remonte" },
      high:    { label: "Haut",       desc: "Commencer et rester HAUT" },
      low:     { label: "Bas",        desc: "Commencer et rester BAS" },
      broken:  { label: "Brisé",      desc: "Gorge tendue, son brisé" },
    },
  },

  ja: {
    appTagline: "どんなフレーズでも話せます。読む必要なし。",
    iSpeak: "私が話す言語",
    iWantToSpeak: "話したい言語",
    placeholder: "日本語でフレーズを入力...",
    sayItButton: "言ってみよう →",
    hearSlowly: "ゆっくり聴く",
    naturalSpeed: "自然なスピード",
    playing: "再生中...",
    stop: "停止",
    sayThisIn: "この言葉を話す：",
    wordByWord: "単語ごとの解説",
    soundsLike: "聞こえ方",
    means: "意味：",
    proTip: "ヒント",
    formalVersion: "丁寧な言い方",
    backToList: "← リストに戻る",
    quickPhrases: "よく使うフレーズ — タップしてすぐ確認",
    customPhrasesNote: "入力したフレーズはAIが生成します",
    instant: "即座",
    generating: "分析中...",
    errorMessage: "エラーが発生しました。もう一度お試しください。",
    toneLabels: {
      rising:  { label: "上昇",   desc: "語尾が上がる" },
      falling: { label: "下降",   desc: "語尾が下がる" },
      flat:    { label: "平坦",   desc: "声を一定に保つ" },
      dipping: { label: "下降上昇", desc: "下がってから上がる" },
      high:    { label: "高",     desc: "高く保つ" },
      low:     { label: "低",     desc: "低く保つ" },
      broken:  { label: "かすれ", desc: "喉を締めた音" },
    },
  },

  ko: {
    appTagline: "어떤 문장이든 말할 수 있어요. 읽기 불필요.",
    iSpeak: "내가 쓰는 언어",
    iWantToSpeak: "말하고 싶은 언어",
    placeholder: "한국어로 문장을 입력하세요...",
    sayItButton: "말해보기 →",
    hearSlowly: "천천히 듣기",
    naturalSpeed: "자연스러운 속도",
    playing: "재생 중...",
    stop: "정지",
    sayThisIn: "이 말을 하세요:",
    wordByWord: "단어별 분석",
    soundsLike: "이렇게 들려요",
    means: "뜻:",
    proTip: "팁",
    formalVersion: "격식체",
    backToList: "← 목록으로 돌아가기",
    quickPhrases: "자주 쓰는 표현 — 탭하면 바로 확인",
    customPhrasesNote: "직접 입력한 문장은 AI가 생성합니다",
    instant: "즉시",
    generating: "분석 중...",
    errorMessage: "오류가 발생했습니다. 다시 시도해 주세요.",
    toneLabels: {
      rising:  { label: "올라감",  desc: "끝에서 목소리가 올라감" },
      falling: { label: "내려감",  desc: "목소리가 내려감" },
      flat:    { label: "평탄",    desc: "목소리를 일정하게 유지" },
      dipping: { label: "내렸다 올라감", desc: "내려갔다가 다시 올라감" },
      high:    { label: "높음",    desc: "높게 시작하고 유지" },
      low:     { label: "낮음",    desc: "낮게 시작하고 유지" },
      broken:  { label: "끊김",    desc: "목이 조여지는 소리" },
    },
  },

  zh: {
    appTagline: "说任何短语，无需阅读。",
    iSpeak: "我说",
    iWantToSpeak: "我想说",
    placeholder: "用中文输入任何短语...",
    sayItButton: "说出来 →",
    hearSlowly: "慢速听",
    naturalSpeed: "正常速度",
    playing: "播放中...",
    stop: "停止",
    sayThisIn: "用这种语言说：",
    wordByWord: "逐词解析",
    soundsLike: "听起来像",
    means: "意思：",
    proTip: "小贴士",
    formalVersion: "正式说法",
    backToList: "← 返回列表",
    quickPhrases: "常用短语 — 点击即查",
    customPhrasesNote: "自定义短语由AI生成",
    instant: "即时",
    generating: "正在分析...",
    errorMessage: "出错了，请重试。",
    toneLabels: {
      rising:  { label: "上升",   desc: "声音在结尾上升" },
      falling: { label: "下降",   desc: "声音下降" },
      flat:    { label: "平",     desc: "保持声音平稳" },
      dipping: { label: "降升",   desc: "先降后升" },
      high:    { label: "高",     desc: "开始并保持高音" },
      low:     { label: "低",     desc: "开始并保持低音" },
      broken:  { label: "入声",   desc: "喉咙收紧，短促音" },
    },
  },

  pt: {
    appTagline: "Fale qualquer frase. Sem necessidade de ler.",
    iSpeak: "Eu falo",
    iWantToSpeak: "Quero falar",
    placeholder: "Digite qualquer frase em português...",
    sayItButton: "FALE →",
    hearSlowly: "Ouvir devagar",
    naturalSpeed: "Velocidade natural",
    playing: "Reproduzindo...",
    stop: "Parar",
    sayThisIn: "Diga isso em",
    wordByWord: "Análise palavra por palavra",
    soundsLike: "Soa como",
    means: "Significa:",
    proTip: "Dica",
    formalVersion: "Versão formal",
    backToList: "← Voltar à lista",
    quickPhrases: "Frases rápidas — toque para ver",
    customPhrasesNote: "Frases personalizadas são geradas por IA",
    instant: "instantâneo",
    generating: "Analisando para você...",
    errorMessage: "Algo deu errado. Por favor tente novamente.",
    toneLabels: {
      rising:  { label: "Subindo",   desc: "Voz SOBE no final" },
      falling: { label: "Descendo",  desc: "Voz DESCE" },
      flat:    { label: "Plano",     desc: "Manter voz NIVELADA" },
      dipping: { label: "Desce-sobe", desc: "Desce depois sobe" },
      high:    { label: "Alto",      desc: "Começar e manter ALTO" },
      low:     { label: "Baixo",     desc: "Começar e manter BAIXO" },
      broken:  { label: "Quebrado",  desc: "Garganta fechada, som cortado" },
    },
  },

  it: {
    appTagline: "Di qualsiasi frase. Senza leggere.",
    iSpeak: "Parlo",
    iWantToSpeak: "Voglio parlare",
    placeholder: "Scrivi qualsiasi frase in italiano...",
    sayItButton: "DILLO →",
    hearSlowly: "Ascolta lentamente",
    naturalSpeed: "Velocità naturale",
    playing: "In riproduzione...",
    stop: "Ferma",
    sayThisIn: "Di' questo in",
    wordByWord: "Analisi parola per parola",
    soundsLike: "Suona come",
    means: "Significa:",
    proTip: "Consiglio",
    formalVersion: "Versione formale",
    backToList: "← Torna alla lista",
    quickPhrases: "Frasi rapide — tocca per vedere",
    customPhrasesNote: "Le frasi personalizzate sono generate dall'IA",
    instant: "immediato",
    generating: "Analizzando per te...",
    errorMessage: "Qualcosa è andato storto. Riprova.",
    toneLabels: {
      rising:  { label: "Ascendente",  desc: "Voce sale alla fine" },
      falling: { label: "Discendente", desc: "Voce scende" },
      flat:    { label: "Piatto",      desc: "Mantieni la voce LIVELLATA" },
      dipping: { label: "Scende-sale", desc: "Scende poi risale" },
      high:    { label: "Alto",        desc: "Inizia e rimani ALTO" },
      low:     { label: "Basso",       desc: "Inizia e rimani BASSO" },
      broken:  { label: "Spezzato",    desc: "Gola tesa, suono spezzato" },
    },
  },

  ar: {
    appTagline: "قل أي جملة. لا حاجة للقراءة.",
    iSpeak: "أتحدث",
    iWantToSpeak: "أريد أن أتحدث",
    placeholder: "اكتب أي جملة بالعربية...",
    sayItButton: "قلها ←",
    hearSlowly: "استمع ببطء",
    naturalSpeed: "السرعة الطبيعية",
    playing: "يُشغَّل...",
    stop: "إيقاف",
    sayThisIn: "قل هذا بـ",
    wordByWord: "تحليل كلمة بكلمة",
    soundsLike: "يشبه",
    means: "يعني:",
    proTip: "نصيحة",
    formalVersion: "النسخة الرسمية",
    backToList: "← العودة إلى القائمة",
    quickPhrases: "عبارات سريعة — اضغط للتحليل الفوري",
    customPhrasesNote: "العبارات المخصصة تُنشأ بالذكاء الاصطناعي",
    instant: "فوري",
    generating: "جارٍ التحليل...",
    errorMessage: "حدث خطأ. يرجى المحاولة مجدداً.",
    toneLabels: {
      rising:  { label: "صاعد",    desc: "الصوت يرتفع في النهاية" },
      falling: { label: "هابط",    desc: "الصوت يهبط" },
      flat:    { label: "مستوٍ",   desc: "الحفاظ على الصوت ثابتاً" },
      dipping: { label: "ينخفض ثم يرتفع", desc: "ينخفض ثم يعود للارتفاع" },
      high:    { label: "مرتفع",   desc: "يبدأ ويبقى مرتفعاً" },
      low:     { label: "منخفض",   desc: "يبدأ ويبقى منخفضاً" },
      broken:  { label: "مكسور",   desc: "صوت متقطع من الحلق" },
    },
  },

  hi: {
    appTagline: "कोई भी वाक्य बोलें। पढ़ने की जरूरत नहीं।",
    iSpeak: "मैं बोलता/बोलती हूँ",
    iWantToSpeak: "मैं बोलना चाहता/चाहती हूँ",
    placeholder: "हिंदी में कोई भी वाक्य लिखें...",
    sayItButton: "बोलो →",
    hearSlowly: "धीरे सुनें",
    naturalSpeed: "सामान्य गति",
    playing: "चल रहा है...",
    stop: "रोकें",
    sayThisIn: "यह इस भाषा में कहें:",
    wordByWord: "शब्द-दर-शब्द विश्लेषण",
    soundsLike: "सुनाई देता है",
    means: "मतलब:",
    proTip: "सुझाव",
    formalVersion: "औपचारिक संस्करण",
    backToList: "← सूची पर वापस जाएं",
    quickPhrases: "त्वरित वाक्य — तुरंत देखने के लिए टैप करें",
    customPhrasesNote: "कस्टम वाक्य AI द्वारा बनाए जाते हैं",
    instant: "तुरंत",
    generating: "विश्लेषण हो रहा है...",
    errorMessage: "कुछ गलत हुआ। कृपया पुनः प्रयास करें।",
    toneLabels: {
      rising:  { label: "ऊपर जाता",  desc: "आवाज़ अंत में ऊपर जाती है" },
      falling: { label: "नीचे जाता", desc: "आवाज़ नीचे जाती है" },
      flat:    { label: "सपाट",      desc: "आवाज़ स्थिर रखें" },
      dipping: { label: "नीचे फिर ऊपर", desc: "नीचे जाकर वापस ऊपर आती है" },
      high:    { label: "ऊंचा",      desc: "ऊंचा शुरू करें और रखें" },
      low:     { label: "नीचा",      desc: "नीचा शुरू करें और रखें" },
      broken:  { label: "टूटा",      desc: "गले से दबा हुआ स्वर" },
    },
  },

  th: {
    appTagline: "พูดประโยคไหนก็ได้ ไม่ต้องอ่าน",
    iSpeak: "ฉันพูด",
    iWantToSpeak: "ฉันอยากพูด",
    placeholder: "พิมพ์ประโยคใดก็ได้เป็นภาษาไทย...",
    sayItButton: "พูดเลย →",
    hearSlowly: "ฟังช้าๆ",
    naturalSpeed: "ความเร็วปกติ",
    playing: "กำลังเล่น...",
    stop: "หยุด",
    sayThisIn: "พูดสิ่งนี้เป็น",
    wordByWord: "วิเคราะห์ทีละคำ",
    soundsLike: "ฟังดูเหมือน",
    means: "หมายความว่า:",
    proTip: "เคล็ดลับ",
    formalVersion: "รูปแบบทางการ",
    backToList: "← กลับสู่รายการ",
    quickPhrases: "ประโยคด่วน — แตะเพื่อดูทันที",
    customPhrasesNote: "ประโยคที่พิมพ์เองสร้างโดย AI",
    instant: "ทันที",
    generating: "กำลังวิเคราะห์...",
    errorMessage: "เกิดข้อผิดพลาด กรุณาลองใหม่",
    toneLabels: {
      rising:  { label: "ขึ้น",      desc: "เสียงขึ้นตอนท้าย" },
      falling: { label: "ลง",       desc: "เสียงลดลง" },
      flat:    { label: "เรียบ",    desc: "รักษาเสียงให้คงที่" },
      dipping: { label: "ลงแล้วขึ้น", desc: "ลงแล้วกลับขึ้น" },
      high:    { label: "สูง",      desc: "เริ่มและคงไว้สูง" },
      low:     { label: "ต่ำ",      desc: "เริ่มและคงไว้ต่ำ" },
      broken:  { label: "ตก",      desc: "เสียงตึงในลำคอ" },
    },
  },
};

export default UI_TEXT;
