// UI_TEXT — all interface strings translated by native language
// Add more languages here as needed

export interface UIStrings {
  phraseLabels: Record<string, string>;
  categoryLabels: Record<string, string>;
  appTagline: string;
  iSpeak: string;
  iWantToSpeak: string;
  placeholder: string;
  sayItButton: string;
  hearSlowly: string;
  naturalSpeed: string;
  playing: string;
  stop: string;
  sayThisIn: string;
  wordByWord: string;
  soundsLike: string;
  means: string;
  proTip: string;
  formalVersion: string;
  backToList: string;
  quickPhrases: string;
  customPhrasesNote: string;
  instant: string;
  generating: string;
  errorMessage: string;
  toneLabels: Record<string, { label: string; desc: string }>;
  // Listen for conversation
  listenLabel?: string;
  listeningLabel?: string;
  stopLabel?: string;
  theyHearLabel?: string;
  youUnderstandLabel?: string;
  literalLabel?: string;
  tryAgainLabel?: string;
  noSpeechSupportLabel?: string;
}

const UI_TEXT: Record<string, UIStrings> = {
  en: {
    categoryLabels: {
      greetings: "Greetings & Basics",
      food: "Food & Dining",
      transport: "Getting Around",
      shopping: "Shopping & Hotels",
      emergency: "Emergency & Health",
    },
    phraseLabels: {
      "hello": "Hello",
      "goodbye": "Goodbye",
      "thank you": "Thank you",
      "thank you very much": "Thank you very much",
      "please": "Please",
      "excuse me": "Excuse me",
      "sorry": "Sorry",
      "yes": "Yes",
      "no": "No",
      "you're welcome": "You're welcome",
      "my name is...": "My name is...",
      "nice to meet you": "Nice to meet you",
      "how are you?": "How are you?",
      "i'm fine, thank you": "I'm fine, thank you",
      "do you speak english?": "Do you speak English?",
      "i don't understand": "I don't understand",
      "can you speak slower?": "Can you speak slower?",
      "cheers!": "Cheers!",
      "good morning": "Good morning",
      "good night": "Good night",
      "the bill please": "The bill please",
      "no ice": "No ice",
      "delicious": "Delicious",
      "one more please": "One more please",
      "water please": "Water please",
      "no spicy": "No spicy",
      "i am vegetarian": "I am vegetarian",
      "i am allergic to peanuts": "I am allergic to peanuts",
      "no MSG please": "No MSG please",
      "what do you recommend?": "What do you recommend?",
      "a table for two": "A table for two",
      "the menu please": "The menu please",
      "do you have...": "Do you have...",
      "well done": "Well done",
      "medium rare": "Medium rare",
      "takeaway please": "Takeaway please",
      "very delicious": "Very delicious",
      "no meat": "No meat",
      "no dairy": "No dairy",
      "can i have the receipt?": "Can I have the receipt?",
      "where is the bathroom?": "Where is the bathroom?",
      "how much is this?": "How much is this?",
      "how far is it?": "How far is it?",
      "turn left": "Turn left",
      "turn right": "Turn right",
      "go straight": "Go straight",
      "stop here": "Stop here",
      "take me to the airport": "Take me to the airport",
      "how much to the airport?": "How much to the airport?",
      "i want to go to...": "I want to go to...",
      "where is the train station?": "Where is the train station?",
      "where is the bus stop?": "Where is the bus stop?",
      "i am lost": "I am lost",
      "can you call a taxi?": "Can you call a taxi?",
      "wait here please": "Wait here please",
      "how long does it take?": "How long does it take?",
      "is it far?": "Is it far?",
      "on the left": "On the left",
      "on the right": "On the right",
      "straight ahead": "Straight ahead",
      "too expensive": "Too expensive",
      "do you have a discount?": "Do you have a discount?",
      "i'll take it": "I'll take it",
      "do you have this in another size?": "Do you have this in another size?",
      "do you have this in another color?": "Do you have this in another color?",
      "can i try it on?": "Can I try it on?",
      "receipt please": "Receipt please",
      "do you accept credit card?": "Do you accept credit card?",
      "i have a reservation": "I have a reservation",
      "check in please": "Check in please",
      "check out please": "Check out please",
      "what time is check out?": "What time is check out?",
      "can i have a room?": "Can I have a room?",
      "is breakfast included?": "Is breakfast included?",
      "the wifi password please": "The wifi password please",
      "my room key please": "My room key please",
      "can you help me?": "Can you help me?",
      "i want a refund": "I want a refund",
      "is there a pharmacy nearby?": "Is there a pharmacy nearby?",
      "help!": "Help!",
      "call the police": "Call the police",
      "call an ambulance": "Call an ambulance",
      "i need a doctor": "I need a doctor",
      "i am sick": "I am sick",
      "i have a fever": "I have a fever",
      "i have a stomach ache": "I have a stomach ache",
      "i am in pain": "I am in pain",
      "i am allergic to...": "I am allergic to...",
      "where is the hospital?": "Where is the hospital?",
      "where is the pharmacy?": "Where is the pharmacy?",
      "i need medicine": "I need medicine",
      "please call this number": "Please call this number",
      "i have lost my passport": "I have lost my passport",
      "i have been robbed": "I have been robbed",
      "i need help": "I need help",
      "is there a doctor nearby?": "Is there a doctor nearby?",
      "this is an emergency": "This is an emergency",
      "please hurry": "Please hurry",
      "i don't feel well": "I don't feel well",
    },
    appTagline: "Speak any phrase. No reading required.",
    iSpeak: "I speak",
    iWantToSpeak: "I want to speak",
    placeholder: "Type any phrase in English...",
    sayItButton: "SAY IT →",
    hearSlowly: "Hear it slowly",
    naturalSpeed: "Natural speed",
    playing: "Playing...",
    stop: "Stop",
    sayThisIn: "Say this in",
    wordByWord: "Word-by-Word Breakdown",
    soundsLike: "Sounds like",
    means: "Means:",
    proTip: "Pro Tip",
    formalVersion: "Formal / Polite Version",
    backToList: "← Back to phrase list",
    quickPhrases: "Quick Phrases — tap for instant breakdown",
    customPhrasesNote: "Custom phrases typed above are AI-generated on the fly",
    instant: "instant",
    generating: "Breaking it down for you...",
    errorMessage: "Something went wrong. Please try again.",
    toneLabels: {
      rising:  { label: "Rising",  desc: "Voice goes UP at the end" },
      falling: { label: "Falling", desc: "Voice goes DOWN" },
      flat:    { label: "Flat",    desc: "Keep voice LEVEL" },
      dipping: { label: "Dipping", desc: "Dips DOWN then back UP" },
      high:    { label: "High",    desc: "Start and stay HIGH" },
      low:     { label: "Low",     desc: "Start and stay LOW" },
      broken:  { label: "Broken",  desc: "Tight throat, creaky sound" },
    },
    listenLabel: "👂 Listen for their response",
    listeningLabel: "Listening — they can speak now",
    stopLabel: "Done",
    theyHearLabel: "They said",
    youUnderstandLabel: "You understand",
    literalLabel: "Literally",
    tryAgainLabel: "Listen again",
    noSpeechSupportLabel: "Speech recognition not supported in this browser. Try Chrome on Android or desktop.",
  },

  vi: {
    categoryLabels: {
      greetings: "Chào hỏi & Cơ bản",
      food: "Ăn uống & Nhà hàng",
      transport: "Di chuyển",
      shopping: "Mua sắm & Khách sạn",
      emergency: "Khẩn cấp & Sức khỏe",
    },
    phraseLabels: {
      "hello": "Xin chào", "goodbye": "Tạm biệt", "thank you": "Cảm ơn", "thank you very much": "Cảm ơn rất nhiều", "please": "Làm ơn", "excuse me": "Xin lỗi", "sorry": "Xin lỗi", "yes": "Có", "no": "Không", "you're welcome": "Không có gì", "my name is...": "Tên tôi là…", "nice to meet you": "Rất vui được gặp bạn", "how are you?": "Bạn khỏe không?", "i'm fine, thank you": "Tôi khỏe, cảm ơn", "do you speak english?": "Bạn có nói tiếng Anh không?", "i don't understand": "Tôi không hiểu", "can you speak slower?": "Bạn có thể nói chậm hơn không?", "cheers!": "Chúc sức khỏe!", "good morning": "Chào buổi sáng", "good night": "Chúc ngủ ngon",
      "the bill please": "Tính tiền", "no ice": "Không đá", "delicious": "Ngon", "one more please": "Thêm một cái nữa", "water please": "Nước lọc", "no spicy": "Không cay", "i am vegetarian": "Tôi ăn chay", "i am allergic to peanuts": "Tôi dị ứng đậu phộng", "no MSG please": "Không bột ngọt", "what do you recommend?": "Bạn gợi ý món gì?", "a table for two": "Bàn cho hai người", "the menu please": "Cho tôi xem menu", "do you have...": "Có … không?", "well done": "Chín kỹ", "medium rare": "Tái", "takeaway please": "Mang về", "very delicious": "Ngon lắm", "no meat": "Không thịt", "no dairy": "Không sữa", "can i have the receipt?": "Cho tôi hóa đơn",
      "where is the bathroom?": "Nhà vệ sinh ở đâu?", "how much is this?": "Cái này bao nhiêu tiền?", "how far is it?": "Bao xa?", "turn left": "Rẽ trái", "turn right": "Rẽ phải", "go straight": "Đi thẳng", "stop here": "Dừng ở đây", "take me to the airport": "Chở tôi đến sân bay", "how much to the airport?": "Đến sân bay bao nhiêu?", "i want to go to...": "Tôi muốn đến…", "where is the train station?": "Ga xe lửa ở đâu?", "where is the bus stop?": "Bến xe buýt ở đâu?", "i am lost": "Tôi bị lạc", "can you call a taxi?": "Bạn có thể gọi taxi không?", "wait here please": "Đợi ở đây", "how long does it take?": "Mất bao lâu?", "is it far?": "Có xa không?", "on the left": "Bên trái", "on the right": "Bên phải", "straight ahead": "Thẳng phía trước",
      "too expensive": "Đắt quá", "do you have a discount?": "Có giảm giá không?", "i'll take it": "Tôi lấy cái này", "do you have this in another size?": "Có size khác không?", "do you have this in another color?": "Có màu khác không?", "can i try it on?": "Tôi mặc thử được không?", "receipt please": "Cho tôi hóa đơn", "do you accept credit card?": "Có nhận thẻ tín dụng không?", "i have a reservation": "Tôi có đặt phòng", "check in please": "Làm thủ tục nhận phòng", "check out please": "Trả phòng", "what time is check out?": "Trả phòng lúc mấy giờ?", "can i have a room?": "Còn phòng không?", "is breakfast included?": "Có bao gồm bữa sáng không?", "the wifi password please": "Mật khẩu wifi", "my room key please": "Chìa khóa phòng", "can you help me?": "Bạn có thể giúp tôi không?", "i want a refund": "Tôi muốn hoàn tiền", "is there a pharmacy nearby?": "Gần đây có nhà thuốc không?",
      "help!": "Cứu tôi!", "call the police": "Gọi cảnh sát", "call an ambulance": "Gọi xe cứu thương", "i need a doctor": "Tôi cần bác sĩ", "i am sick": "Tôi bị bệnh", "i have a fever": "Tôi bị sốt", "i have a stomach ache": "Tôi đau bụng", "i am in pain": "Tôi đang đau", "i am allergic to...": "Tôi dị ứng với…", "where is the hospital?": "Bệnh viện ở đâu?", "where is the pharmacy?": "Nhà thuốc ở đâu?", "i need medicine": "Tôi cần thuốc", "please call this number": "Gọi số này giúp tôi", "i have lost my passport": "Tôi mất hộ chiếu", "i have been robbed": "Tôi bị cướp", "i need help": "Tôi cần giúp đỡ", "is there a doctor nearby?": "Gần đây có bác sĩ không?", "this is an emergency": "Đây là tình huống khẩn cấp", "please hurry": "Hãy nhanh lên", "i don't feel well": "Tôi không khỏe",
    },
    appTagline: "Nói bất kỳ câu nào. Không cần đọc.",
    iSpeak: "Tôi nói",
    iWantToSpeak: "Tôi muốn nói",
    placeholder: "Nhập bất kỳ câu nào bằng tiếng Việt...",
    sayItButton: "NÓI NÀO →",
    hearSlowly: "Nghe chậm",
    naturalSpeed: "Tốc độ bình thường",
    playing: "Đang phát...",
    stop: "Dừng",
    sayThisIn: "Nói câu này bằng",
    wordByWord: "Phân tích từng từ",
    soundsLike: "Nghe giống như",
    means: "Nghĩa:",
    proTip: "Mẹo hay",
    formalVersion: "Phiên bản trang trọng",
    backToList: "← Quay lại danh sách",
    quickPhrases: "Câu thông dụng — nhấn để xem ngay",
    customPhrasesNote: "Câu tự nhập sẽ được AI tạo ra",
    instant: "ngay",
    generating: "Đang phân tích cho bạn...",
    errorMessage: "Có lỗi xảy ra. Vui lòng thử lại.",
    toneLabels: {
      rising:  { label: "Lên",      desc: "Giọng đi LÊN cuối câu" },
      falling: { label: "Xuống",    desc: "Giọng đi XUỐNG" },
      flat:    { label: "Bằng",     desc: "Giữ giọng PHẲNG" },
      dipping: { label: "Xuống rồi lên", desc: "Giọng xuống rồi lên lại" },
      high:    { label: "Cao",      desc: "Bắt đầu và giữ CAO" },
      low:     { label: "Thấp",     desc: "Bắt đầu và giữ THẤP" },
      broken:  { label: "Gãy",      desc: "Cổ họng căng, giọng ngắt" },
    },
    listenLabel: "👂 Nghe phản hồi của họ",
    listeningLabel: "Đang nghe — họ có thể nói bây giờ",
    stopLabel: "Xong",
    theyHearLabel: "Họ nói",
    youUnderstandLabel: "Bạn hiểu",
    literalLabel: "Nghĩa đen",
    tryAgainLabel: "Nghe lại",
    noSpeechSupportLabel: "Trình duyệt không hỗ trợ nhận dạng giọng nói. Hãy dùng Chrome.",
    listenLabel: "👂 Escuchar su respuesta",
    listeningLabel: "Escuchando — pueden hablar ahora",
    stopLabel: "Listo",
    theyHearLabel: "Ellos dijeron",
    youUnderstandLabel: "Tú entiendes",
    literalLabel: "Literalmente",
    tryAgainLabel: "Escuchar de nuevo",
    noSpeechSupportLabel: "Reconocimiento de voz no disponible en este navegador. Prueba Chrome.",
  },

  es: {
    categoryLabels: { greetings: "Saludos y básicos", food: "Comida y restaurantes", transport: "Cómo moverse", shopping: "Compras y hoteles", emergency: "Emergencias y salud" },
    phraseLabels: { "hello": "Hola", "goodbye": "Adiós", "thank you": "Gracias", "thank you very much": "Muchas gracias", "please": "Por favor", "excuse me": "Perdón", "sorry": "Lo siento", "yes": "Sí", "no": "No", "you're welcome": "De nada", "my name is...": "Me llamo…", "nice to meet you": "Encantado/a", "how are you?": "¿Cómo estás?", "i'm fine, thank you": "Bien, gracias", "do you speak english?": "¿Hablas inglés?", "i don't understand": "No entiendo", "can you speak slower?": "¿Puedes hablar más despacio?", "cheers!": "¡Salud!", "good morning": "Buenos días", "good night": "Buenas noches", "the bill please": "La cuenta, por favor", "no ice": "Sin hielo", "delicious": "Delicioso", "one more please": "Uno más, por favor", "water please": "Agua, por favor", "no spicy": "Sin picante", "i am vegetarian": "Soy vegetariano/a", "i am allergic to peanuts": "Soy alérgico a los cacahuetes", "no MSG please": "Sin glutamato", "what do you recommend?": "¿Qué recomiendas?", "a table for two": "Una mesa para dos", "the menu please": "El menú, por favor", "do you have...": "¿Tienes…?", "well done": "Muy hecho", "medium rare": "Poco hecho", "takeaway please": "Para llevar", "very delicious": "Muy delicioso", "no meat": "Sin carne", "no dairy": "Sin lácteos", "can i have the receipt?": "¿Me da el recibo?", "where is the bathroom?": "¿Dónde está el baño?", "how much is this?": "¿Cuánto cuesta esto?", "how far is it?": "¿Qué tan lejos está?", "turn left": "Gire a la izquierda", "turn right": "Gire a la derecha", "go straight": "Siga recto", "stop here": "Pare aquí", "take me to the airport": "Llévame al aeropuerto", "how much to the airport?": "¿Cuánto al aeropuerto?", "i want to go to...": "Quiero ir a…", "where is the train station?": "¿Dónde está la estación?", "where is the bus stop?": "¿Dónde está la parada?", "i am lost": "Estoy perdido/a", "can you call a taxi?": "¿Puede llamar un taxi?", "wait here please": "Espere aquí", "how long does it take?": "¿Cuánto tarda?", "is it far?": "¿Está lejos?", "on the left": "A la izquierda", "on the right": "A la derecha", "straight ahead": "Todo recto", "too expensive": "Muy caro", "do you have a discount?": "¿Hay descuento?", "i'll take it": "Me lo llevo", "do you have this in another size?": "¿Lo tiene en otra talla?", "do you have this in another color?": "¿Lo tiene en otro color?", "can i try it on?": "¿Puedo probármelo?", "receipt please": "El recibo, por favor", "do you accept credit card?": "¿Acepta tarjeta?", "i have a reservation": "Tengo una reserva", "check in please": "Hacer check-in", "check out please": "Hacer check-out", "what time is check out?": "¿A qué hora es el check-out?", "can i have a room?": "¿Tiene habitación?", "is breakfast included?": "¿Está incluido el desayuno?", "the wifi password please": "La contraseña del wifi", "my room key please": "La llave de mi habitación", "can you help me?": "¿Puede ayudarme?", "i want a refund": "Quiero un reembolso", "is there a pharmacy nearby?": "¿Hay una farmacia cerca?", "help!": "¡Ayuda!", "call the police": "Llame a la policía", "call an ambulance": "Llame a una ambulancia", "i need a doctor": "Necesito un médico", "i am sick": "Estoy enfermo/a", "i have a fever": "Tengo fiebre", "i have a stomach ache": "Me duele el estómago", "i am in pain": "Tengo dolor", "i am allergic to...": "Soy alérgico a…", "where is the hospital?": "¿Dónde está el hospital?", "where is the pharmacy?": "¿Dónde está la farmacia?", "i need medicine": "Necesito medicamento", "please call this number": "Llame a este número", "i have lost my passport": "He perdido mi pasaporte", "i have been robbed": "Me han robado", "i need help": "Necesito ayuda", "is there a doctor nearby?": "¿Hay médico cerca?", "this is an emergency": "Es una emergencia", "please hurry": "Dese prisa", "i don't feel well": "No me siento bien" },
    appTagline: "Di cualquier frase. Sin necesidad de leer.",
    iSpeak: "Yo hablo",
    iWantToSpeak: "Quiero hablar",
    placeholder: "Escribe cualquier frase en español...",
    sayItButton: "¡DILO →",
    hearSlowly: "Escuchar despacio",
    naturalSpeed: "Velocidad natural",
    playing: "Reproduciendo...",
    stop: "Detener",
    sayThisIn: "Di esto en",
    wordByWord: "Desglose palabra por palabra",
    soundsLike: "Suena como",
    means: "Significa:",
    proTip: "Consejo",
    formalVersion: "Versión formal",
    backToList: "← Volver a la lista",
    quickPhrases: "Frases rápidas — toca para ver",
    customPhrasesNote: "Las frases personalizadas son generadas por IA",
    instant: "al instante",
    generating: "Analizando para ti...",
    errorMessage: "Algo salió mal. Por favor intenta de nuevo.",
    toneLabels: {
      rising:  { label: "Ascendente",  desc: "La voz SUBE al final" },
      falling: { label: "Descendente", desc: "La voz BAJA" },
      flat:    { label: "Plano",       desc: "Mantén la voz NIVELADA" },
      dipping: { label: "Baja y sube", desc: "Baja y luego SUBE" },
      high:    { label: "Alto",        desc: "Empieza y mantén ALTO" },
      low:     { label: "Bajo",        desc: "Empieza y mantén BAJO" },
      broken:  { label: "Cortado",     desc: "Garganta tensa, sonido cortado" },
    },
    listenLabel: "👂 Auf Antwort hören",
    listeningLabel: "Höre zu — sie können jetzt sprechen",
    stopLabel: "Fertig",
    theyHearLabel: "Sie sagten",
    youUnderstandLabel: "Du verstehst",
    literalLabel: "Wörtlich",
    tryAgainLabel: "Nochmal zuhören",
    noSpeechSupportLabel: "Spracherkennung nicht unterstützt. Bitte Chrome verwenden.",
  },

  de: {
    categoryLabels: { greetings: "Begrüßung & Grundlagen", food: "Essen & Trinken", transport: "Unterwegs", shopping: "Einkaufen & Hotels", emergency: "Notfall & Gesundheit" },
    phraseLabels: { "hello": "Hallo", "goodbye": "Auf Wiedersehen", "thank you": "Danke", "thank you very much": "Vielen Dank", "please": "Bitte", "excuse me": "Entschuldigung", "sorry": "Es tut mir leid", "yes": "Ja", "no": "Nein", "you're welcome": "Bitte sehr", "my name is...": "Mein Name ist…", "nice to meet you": "Schön, Sie kennenzulernen", "how are you?": "Wie geht es Ihnen?", "i'm fine, thank you": "Gut, danke", "do you speak english?": "Sprechen Sie Englisch?", "i don't understand": "Ich verstehe nicht", "can you speak slower?": "Können Sie langsamer sprechen?", "cheers!": "Prost!", "good morning": "Guten Morgen", "good night": "Gute Nacht", "the bill please": "Die Rechnung, bitte", "no ice": "Ohne Eis", "delicious": "Lecker", "one more please": "Noch einen, bitte", "water please": "Wasser, bitte", "no spicy": "Nicht scharf", "i am vegetarian": "Ich bin Vegetarier", "i am allergic to peanuts": "Ich bin allergisch gegen Erdnüsse", "no MSG please": "Kein Glutamat", "what do you recommend?": "Was empfehlen Sie?", "a table for two": "Ein Tisch für zwei", "the menu please": "Die Speisekarte, bitte", "do you have...": "Haben Sie…?", "well done": "Durchgebraten", "medium rare": "Medium rare", "takeaway please": "Zum Mitnehmen", "very delicious": "Sehr lecker", "no meat": "Ohne Fleisch", "no dairy": "Ohne Milchprodukte", "can i have the receipt?": "Den Kassenbon, bitte", "where is the bathroom?": "Wo ist die Toilette?", "how much is this?": "Was kostet das?", "how far is it?": "Wie weit ist es?", "turn left": "Links abbiegen", "turn right": "Rechts abbiegen", "go straight": "Geradeaus", "stop here": "Hier anhalten", "take me to the airport": "Zum Flughafen, bitte", "how much to the airport?": "Was kostet es zum Flughafen?", "i want to go to...": "Ich möchte zu…", "where is the train station?": "Wo ist der Bahnhof?", "where is the bus stop?": "Wo ist die Bushaltestelle?", "i am lost": "Ich habe mich verlaufen", "can you call a taxi?": "Können Sie ein Taxi rufen?", "wait here please": "Warten Sie hier", "how long does it take?": "Wie lange dauert es?", "is it far?": "Ist es weit?", "on the left": "Links", "on the right": "Rechts", "straight ahead": "Geradeaus", "too expensive": "Zu teuer", "do you have a discount?": "Gibt es Rabatt?", "i'll take it": "Ich nehme es", "do you have this in another size?": "Haben Sie das in einer anderen Größe?", "do you have this in another color?": "Haben Sie das in einer anderen Farbe?", "can i try it on?": "Kann ich es anprobieren?", "receipt please": "Quittung, bitte", "do you accept credit card?": "Akzeptieren Sie Kreditkarten?", "i have a reservation": "Ich habe eine Reservierung", "check in please": "Einchecken, bitte", "check out please": "Auschecken, bitte", "what time is check out?": "Wann ist Check-out?", "can i have a room?": "Haben Sie ein Zimmer?", "is breakfast included?": "Ist Frühstück inbegriffen?", "the wifi password please": "Das WLAN-Passwort, bitte", "my room key please": "Meinen Zimmerschlüssel, bitte", "can you help me?": "Können Sie mir helfen?", "i want a refund": "Ich möchte eine Rückerstattung", "is there a pharmacy nearby?": "Gibt es eine Apotheke in der Nähe?", "help!": "Hilfe!", "call the police": "Rufen Sie die Polizei", "call an ambulance": "Rufen Sie einen Krankenwagen", "i need a doctor": "Ich brauche einen Arzt", "i am sick": "Ich bin krank", "i have a fever": "Ich habe Fieber", "i have a stomach ache": "Ich habe Bauchschmerzen", "i am in pain": "Ich habe Schmerzen", "i am allergic to...": "Ich bin allergisch gegen…", "where is the hospital?": "Wo ist das Krankenhaus?", "where is the pharmacy?": "Wo ist die Apotheke?", "i need medicine": "Ich brauche Medizin", "please call this number": "Bitte rufen Sie diese Nummer an", "i have lost my passport": "Ich habe meinen Pass verloren", "i have been robbed": "Ich wurde bestohlen", "i need help": "Ich brauche Hilfe", "is there a doctor nearby?": "Gibt es einen Arzt in der Nähe?", "this is an emergency": "Dies ist ein Notfall", "please hurry": "Bitte beeilen Sie sich", "i don't feel well": "Ich fühle mich nicht wohl" },
    appTagline: "Sag jeden Satz. Kein Lesen erforderlich.",
    iSpeak: "Ich spreche",
    iWantToSpeak: "Ich möchte sprechen",
    placeholder: "Gib einen Satz auf Deutsch ein...",
    sayItButton: "SAG ES →",
    hearSlowly: "Langsam anhören",
    naturalSpeed: "Normale Geschwindigkeit",
    playing: "Wird abgespielt...",
    stop: "Stopp",
    sayThisIn: "Sag das auf",
    wordByWord: "Wort-für-Wort-Aufschlüsselung",
    soundsLike: "Klingt wie",
    means: "Bedeutet:",
    proTip: "Tipp",
    formalVersion: "Formelle Version",
    backToList: "← Zurück zur Liste",
    quickPhrases: "Schnellphrasen — tippen für sofortige Analyse",
    customPhrasesNote: "Eigene Phrasen werden von KI generiert",
    instant: "sofort",
    generating: "Wird analysiert...",
    errorMessage: "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    toneLabels: {
      rising:  { label: "Steigend",   desc: "Stimme geht AM ENDE hoch" },
      falling: { label: "Fallend",    desc: "Stimme geht RUNTER" },
      flat:    { label: "Flach",      desc: "Stimme GLEICHMÄSSIG halten" },
      dipping: { label: "Tief-hoch",  desc: "Runter dann wieder hoch" },
      high:    { label: "Hoch",       desc: "Hoch beginnen und halten" },
      low:     { label: "Tief",       desc: "Tief beginnen und halten" },
      broken:  { label: "Gebrochen",  desc: "Kehle angespannt, Knacklaut" },
    },
    listenLabel: "👂 Luister naar hun antwoord",
    listeningLabel: "Luisteren — ze kunnen nu spreken",
    stopLabel: "Klaar",
    theyHearLabel: "Zij zeiden",
    youUnderstandLabel: "Jij begrijpt",
    literalLabel: "Letterlijk",
    tryAgainLabel: "Opnieuw luisteren",
    noSpeechSupportLabel: "Spraakherkenning niet ondersteund. Probeer Chrome.",
  },

  nl: {
    categoryLabels: { greetings: "Begroetingen & Basis", food: "Eten & Drinken", transport: "Onderweg", shopping: "Winkelen & Hotels", emergency: "Noodgeval & Gezondheid" },
    phraseLabels: { "hello": "Hallo", "goodbye": "Tot ziens", "thank you": "Dank je", "thank you very much": "Hartelijk dank", "please": "Alsjeblieft", "excuse me": "Excuseer me", "sorry": "Sorry", "yes": "Ja", "no": "Nee", "you're welcome": "Graag gedaan", "my name is...": "Mijn naam is…", "nice to meet you": "Aangenaam", "how are you?": "Hoe gaat het?", "i'm fine, thank you": "Goed, dank je", "do you speak english?": "Spreekt u Engels?", "i don't understand": "Ik begrijp het niet", "can you speak slower?": "Kunt u langzamer spreken?", "cheers!": "Proost!", "good morning": "Goedemorgen", "good night": "Goedenacht", "the bill please": "De rekening, alstublieft", "no ice": "Zonder ijs", "delicious": "Heerlijk", "one more please": "Nog één, alsjeblieft", "water please": "Water, alsjeblieft", "no spicy": "Niet pittig", "i am vegetarian": "Ik ben vegetariër", "i am allergic to peanuts": "Ik ben allergisch voor pinda's", "no MSG please": "Geen MSG", "what do you recommend?": "Wat raadt u aan?", "a table for two": "Een tafel voor twee", "the menu please": "De menukaart, alstublieft", "do you have...": "Heeft u…?", "well done": "Doorbakken", "medium rare": "Medium rare", "takeaway please": "Meenemen, alstublieft", "very delicious": "Erg lekker", "no meat": "Zonder vlees", "no dairy": "Zonder zuivel", "can i have the receipt?": "De bon, alstublieft", "where is the bathroom?": "Waar is het toilet?", "how much is this?": "Hoeveel kost dit?", "how far is it?": "Hoe ver is het?", "turn left": "Links afslaan", "turn right": "Rechts afslaan", "go straight": "Rechtdoor", "stop here": "Hier stoppen", "take me to the airport": "Naar het vliegveld", "how much to the airport?": "Hoeveel naar het vliegveld?", "i want to go to...": "Ik wil naar…", "where is the train station?": "Waar is het station?", "where is the bus stop?": "Waar is de bushalte?", "i am lost": "Ik ben verdwaald", "can you call a taxi?": "Kunt u een taxi bellen?", "wait here please": "Wacht hier", "how long does it take?": "Hoe lang duurt het?", "is it far?": "Is het ver?", "on the left": "Links", "on the right": "Rechts", "straight ahead": "Rechtdoor", "too expensive": "Te duur", "do you have a discount?": "Is er korting?", "i'll take it": "Ik neem het", "do you have this in another size?": "Heeft u dit in een andere maat?", "do you have this in another color?": "Heeft u dit in een andere kleur?", "can i try it on?": "Mag ik het passen?", "receipt please": "Bon, alstublieft", "do you accept credit card?": "Accepteert u creditcard?", "i have a reservation": "Ik heb een reservering", "check in please": "Inchecken", "check out please": "Uitchecken", "what time is check out?": "Hoe laat is uitchecken?", "can i have a room?": "Heeft u een kamer?", "is breakfast included?": "Is ontbijt inbegrepen?", "the wifi password please": "Het wifi-wachtwoord", "my room key please": "Mijn kamersleutel", "can you help me?": "Kunt u mij helpen?", "i want a refund": "Ik wil mijn geld terug", "is there a pharmacy nearby?": "Is er een apotheek in de buurt?", "help!": "Help!", "call the police": "Bel de politie", "call an ambulance": "Bel een ambulance", "i need a doctor": "Ik heb een dokter nodig", "i am sick": "Ik ben ziek", "i have a fever": "Ik heb koorts", "i have a stomach ache": "Ik heb buikpijn", "i am in pain": "Ik heb pijn", "i am allergic to...": "Ik ben allergisch voor…", "where is the hospital?": "Waar is het ziekenhuis?", "where is the pharmacy?": "Waar is de apotheek?", "i need medicine": "Ik heb medicijnen nodig", "please call this number": "Bel dit nummer", "i have lost my passport": "Ik ben mijn paspoort kwijt", "i have been robbed": "Ik ben beroofd", "i need help": "Ik heb hulp nodig", "is there a doctor nearby?": "Is er een dokter in de buurt?", "this is an emergency": "Dit is een noodgeval", "please hurry": "Schiet op, alstublieft", "i don't feel well": "Ik voel me niet goed" },
    appTagline: "Spreek elke zin uit. Geen lezen vereist.",
    iSpeak: "Ik spreek",
    iWantToSpeak: "Ik wil spreken",
    placeholder: "Typ een zin in het Nederlands...",
    sayItButton: "ZEG HET →",
    hearSlowly: "Langzaam beluisteren",
    naturalSpeed: "Normale snelheid",
    playing: "Wordt afgespeeld...",
    stop: "Stop",
    sayThisIn: "Zeg dit in het",
    wordByWord: "Woord-voor-woord uitleg",
    soundsLike: "Klinkt als",
    means: "Betekent:",
    proTip: "Tip",
    formalVersion: "Formele versie",
    backToList: "← Terug naar de lijst",
    quickPhrases: "Snelle zinnen — tik voor directe uitleg",
    customPhrasesNote: "Eigen zinnen worden door AI gegenereerd",
    instant: "direct",
    generating: "Wordt geanalyseerd...",
    errorMessage: "Er is iets misgegaan. Probeer opnieuw.",
    toneLabels: {
      rising:  { label: "Stijgend",  desc: "Stem gaat OMHOOG aan het einde" },
      falling: { label: "Dalend",    desc: "Stem gaat OMLAAG" },
      flat:    { label: "Vlak",      desc: "Stem GELIJK houden" },
      dipping: { label: "Dal-stijg", desc: "Omlaag dan weer omhoog" },
      high:    { label: "Hoog",      desc: "Begin en blijf HOOG" },
      low:     { label: "Laag",      desc: "Begin en blijf LAAG" },
      broken:  { label: "Gebroken",  desc: "Gespannen keel, krakend geluid" },
    },
    listenLabel: "👂 Écouter leur réponse",
    listeningLabel: "Écoute en cours — ils peuvent parler",
    stopLabel: "Terminé",
    theyHearLabel: "Ils ont dit",
    youUnderstandLabel: "Vous comprenez",
    literalLabel: "Littéralement",
    tryAgainLabel: "Écouter à nouveau",
    noSpeechSupportLabel: "Reconnaissance vocale non supportée. Essayez Chrome.",
  },

  fr: {
    categoryLabels: { greetings: "Salutations & Bases", food: "Nourriture & Restaurants", transport: "Se déplacer", shopping: "Shopping & Hôtels", emergency: "Urgences & Santé" },
    phraseLabels: { "hello": "Bonjour", "goodbye": "Au revoir", "thank you": "Merci", "thank you very much": "Merci beaucoup", "please": "S'il vous plaît", "excuse me": "Excusez-moi", "sorry": "Désolé", "yes": "Oui", "no": "Non", "you're welcome": "De rien", "my name is...": "Je m'appelle…", "nice to meet you": "Enchanté", "how are you?": "Comment allez-vous?", "i'm fine, thank you": "Bien, merci", "do you speak english?": "Parlez-vous anglais?", "i don't understand": "Je ne comprends pas", "can you speak slower?": "Pouvez-vous parler plus lentement?", "cheers!": "Santé!", "good morning": "Bonjour", "good night": "Bonne nuit", "the bill please": "L'addition, s'il vous plaît", "no ice": "Sans glace", "delicious": "Délicieux", "one more please": "Encore un, s'il vous plaît", "water please": "De l'eau, s'il vous plaît", "no spicy": "Pas épicé", "i am vegetarian": "Je suis végétarien", "i am allergic to peanuts": "Je suis allergique aux arachides", "no MSG please": "Sans glutamate", "what do you recommend?": "Que recommandez-vous?", "a table for two": "Une table pour deux", "the menu please": "Le menu, s'il vous plaît", "do you have...": "Avez-vous…?", "well done": "Bien cuit", "medium rare": "Saignant", "takeaway please": "À emporter", "very delicious": "Très délicieux", "no meat": "Sans viande", "no dairy": "Sans produits laitiers", "can i have the receipt?": "Le reçu, s'il vous plaît", "where is the bathroom?": "Où sont les toilettes?", "how much is this?": "Combien ça coûte?", "how far is it?": "C'est loin?", "turn left": "Tournez à gauche", "turn right": "Tournez à droite", "go straight": "Allez tout droit", "stop here": "Arrêtez-vous ici", "take me to the airport": "Emmenez-moi à l'aéroport", "how much to the airport?": "Combien jusqu'à l'aéroport?", "i want to go to...": "Je veux aller à…", "where is the train station?": "Où est la gare?", "where is the bus stop?": "Où est l'arrêt de bus?", "i am lost": "Je suis perdu", "can you call a taxi?": "Pouvez-vous appeler un taxi?", "wait here please": "Attendez ici", "how long does it take?": "Combien de temps faut-il?", "is it far?": "C'est loin?", "on the left": "À gauche", "on the right": "À droite", "straight ahead": "Tout droit", "too expensive": "Trop cher", "do you have a discount?": "Y a-t-il une réduction?", "i'll take it": "Je le prends", "do you have this in another size?": "Avez-vous ceci dans une autre taille?", "do you have this in another color?": "Avez-vous ceci dans une autre couleur?", "can i try it on?": "Puis-je l'essayer?", "receipt please": "Le reçu, s'il vous plaît", "do you accept credit card?": "Acceptez-vous les cartes?", "i have a reservation": "J'ai une réservation", "check in please": "Enregistrement", "check out please": "Départ", "what time is check out?": "À quelle heure est le départ?", "can i have a room?": "Avez-vous une chambre?", "is breakfast included?": "Le petit-déjeuner est-il inclus?", "the wifi password please": "Le mot de passe wifi", "my room key please": "Ma clé de chambre", "can you help me?": "Pouvez-vous m'aider?", "i want a refund": "Je veux un remboursement", "is there a pharmacy nearby?": "Y a-t-il une pharmacie?", "help!": "Au secours!", "call the police": "Appelez la police", "call an ambulance": "Appelez une ambulance", "i need a doctor": "J'ai besoin d'un médecin", "i am sick": "Je suis malade", "i have a fever": "J'ai de la fièvre", "i have a stomach ache": "J'ai mal au ventre", "i am in pain": "J'ai mal", "i am allergic to...": "Je suis allergique à…", "where is the hospital?": "Où est l'hôpital?", "where is the pharmacy?": "Où est la pharmacie?", "i need medicine": "J'ai besoin de médicaments", "please call this number": "Appelez ce numéro", "i have lost my passport": "J'ai perdu mon passeport", "i have been robbed": "J'ai été volé", "i need help": "J'ai besoin d'aide", "is there a doctor nearby?": "Y a-t-il un médecin?", "this is an emergency": "C'est une urgence", "please hurry": "Dépêchez-vous", "i don't feel well": "Je ne me sens pas bien" },
    appTagline: "Dites n'importe quelle phrase. Sans lecture.",
    iSpeak: "Je parle",
    iWantToSpeak: "Je veux parler",
    placeholder: "Tapez n'importe quelle phrase en français...",
    sayItButton: "DITES-LE →",
    hearSlowly: "Écouter lentement",
    naturalSpeed: "Vitesse naturelle",
    playing: "Lecture en cours...",
    stop: "Arrêter",
    sayThisIn: "Dites ceci en",
    wordByWord: "Décomposition mot par mot",
    soundsLike: "Ça ressemble à",
    means: "Signifie :",
    proTip: "Conseil",
    formalVersion: "Version formelle",
    backToList: "← Retour à la liste",
    quickPhrases: "Phrases rapides — appuyez pour voir",
    customPhrasesNote: "Les phrases personnalisées sont générées par l'IA",
    instant: "instantané",
    generating: "Analyse en cours...",
    errorMessage: "Une erreur s'est produite. Veuillez réessayer.",
    toneLabels: {
      rising:  { label: "Montant",    desc: "La voix MONTE à la fin" },
      falling: { label: "Descendant", desc: "La voix DESCEND" },
      flat:    { label: "Plat",       desc: "Garder la voix STABLE" },
      dipping: { label: "Bas-haut",   desc: "Descend puis remonte" },
      high:    { label: "Haut",       desc: "Commencer et rester HAUT" },
      low:     { label: "Bas",        desc: "Commencer et rester BAS" },
      broken:  { label: "Brisé",      desc: "Gorge tendue, son brisé" },
    },
    listenLabel: "👂 返事を聞く",
    listeningLabel: "聞いています — 話してください",
    stopLabel: "完了",
    theyHearLabel: "相手が言った",
    youUnderstandLabel: "あなたが理解する",
    literalLabel: "直訳",
    tryAgainLabel: "もう一度聞く",
    noSpeechSupportLabel: "このブラウザは音声認識に対応していません。Chromeをお試しください。",
  },

  ja: {
    categoryLabels: {
      greetings: "挨拶・基本",
      food: "食事・飲食",
      transport: "移動・交通",
      shopping: "買い物・ホテル",
      emergency: "緊急・医療",
    },
    phraseLabels: {
      "hello": "こんにちは",
      "goodbye": "さようなら",
      "thank you": "ありがとう",
      "thank you very much": "ありがとうございます",
      "please": "お願いします",
      "excuse me": "すみません",
      "sorry": "ごめんなさい",
      "yes": "はい",
      "no": "いいえ",
      "you're welcome": "どういたしまして",
      "my name is...": "私の名前は…",
      "nice to meet you": "はじめまして",
      "how are you?": "お元気ですか？",
      "i'm fine, thank you": "元気です、ありがとう",
      "do you speak english?": "英語は話せますか？",
      "i don't understand": "わかりません",
      "can you speak slower?": "ゆっくり話してください",
      "cheers!": "乾杯！",
      "good morning": "おはようございます",
      "good night": "おやすみなさい",
      "the bill please": "お会計をお願いします",
      "no ice": "氷なしで",
      "delicious": "おいしい",
      "one more please": "もう一つください",
      "water please": "水をください",
      "no spicy": "辛くしないで",
      "i am vegetarian": "私はベジタリアンです",
      "i am allergic to peanuts": "ピーナッツアレルギーがあります",
      "no MSG please": "化学調味料なしで",
      "what do you recommend?": "おすすめは何ですか？",
      "a table for two": "2人用のテーブルを",
      "the menu please": "メニューをください",
      "do you have...": "…はありますか？",
      "well done": "よく焼いて",
      "medium rare": "ミディアムレアで",
      "takeaway please": "持ち帰りで",
      "very delicious": "とても美味しい",
      "no meat": "肉なしで",
      "no dairy": "乳製品なしで",
      "can i have the receipt?": "レシートをください",
      "where is the bathroom?": "トイレはどこですか？",
      "how much is this?": "これはいくらですか？",
      "how far is it?": "どのくらい遠いですか？",
      "turn left": "左に曲がって",
      "turn right": "右に曲がって",
      "go straight": "まっすぐ進んで",
      "stop here": "ここで止めて",
      "take me to the airport": "空港まで連れて行って",
      "how much to the airport?": "空港までいくらですか？",
      "i want to go to...": "…に行きたい",
      "where is the train station?": "駅はどこですか？",
      "where is the bus stop?": "バス停はどこですか？",
      "i am lost": "迷子になりました",
      "can you call a taxi?": "タクシーを呼んでもらえますか？",
      "wait here please": "ここで待っていて",
      "how long does it take?": "どのくらいかかりますか？",
      "is it far?": "遠いですか？",
      "on the left": "左側に",
      "on the right": "右側に",
      "straight ahead": "まっすぐ前",
      "too expensive": "高すぎます",
      "do you have a discount?": "割引はありますか？",
      "i'll take it": "これをください",
      "do you have this in another size?": "別のサイズはありますか？",
      "do you have this in another color?": "別の色はありますか？",
      "can i try it on?": "試着できますか？",
      "receipt please": "領収書をください",
      "do you accept credit card?": "クレジットカードは使えますか？",
      "i have a reservation": "予約があります",
      "check in please": "チェックインをお願いします",
      "check out please": "チェックアウトをお願いします",
      "what time is check out?": "チェックアウトは何時ですか？",
      "can i have a room?": "部屋はありますか？",
      "is breakfast included?": "朝食は含まれていますか？",
      "the wifi password please": "WiFiのパスワードを教えて",
      "my room key please": "部屋の鍵をください",
      "can you help me?": "助けてもらえますか？",
      "i want a refund": "返金してください",
      "is there a pharmacy nearby?": "近くに薬局はありますか？",
      "help!": "助けて！",
      "call the police": "警察を呼んで",
      "call an ambulance": "救急車を呼んで",
      "i need a doctor": "医者が必要です",
      "i am sick": "具合が悪いです",
      "i have a fever": "熱があります",
      "i have a stomach ache": "お腹が痛いです",
      "i am in pain": "痛いです",
      "i am allergic to...": "…にアレルギーがあります",
      "where is the hospital?": "病院はどこですか？",
      "where is the pharmacy?": "薬局はどこですか？",
      "i need medicine": "薬が必要です",
      "please call this number": "この番号に電話して",
      "i have lost my passport": "パスポートをなくしました",
      "i have been robbed": "盗まれました",
      "i need help": "助けが必要です",
      "is there a doctor nearby?": "近くに医者はいますか？",
      "this is an emergency": "緊急事態です",
      "please hurry": "急いでください",
      "i don't feel well": "気分が悪いです",
    },
    appTagline: "どんなフレーズでも話せます。読む必要なし。",
    iSpeak: "私が話す言語",
    iWantToSpeak: "話したい言語",
    placeholder: "日本語でフレーズを入力...",
    sayItButton: "言ってみよう →",
    hearSlowly: "ゆっくり聴く",
    naturalSpeed: "自然なスピード",
    playing: "再生中...",
    stop: "停止",
    sayThisIn: "この言葉を話す：",
    wordByWord: "単語ごとの解説",
    soundsLike: "聞こえ方",
    means: "意味：",
    proTip: "ヒント",
    formalVersion: "丁寧な言い方",
    backToList: "← リストに戻る",
    quickPhrases: "よく使うフレーズ — タップしてすぐ確認",
    customPhrasesNote: "入力したフレーズはAIが生成します",
    instant: "即座",
    generating: "分析中...",
    errorMessage: "エラーが発生しました。もう一度お試しください。",
    toneLabels: {
      rising:  { label: "上昇",   desc: "語尾が上がる" },
      falling: { label: "下降",   desc: "語尾が下がる" },
      flat:    { label: "平坦",   desc: "声を一定に保つ" },
      dipping: { label: "下降上昇", desc: "下がってから上がる" },
      high:    { label: "高",     desc: "高く保つ" },
      low:     { label: "低",     desc: "低く保つ" },
      broken:  { label: "かすれ", desc: "喉を締めた音" },
    },
    listenLabel: "👂 응답 듣기",
    listeningLabel: "듣는 중 — 지금 말할 수 있어요",
    stopLabel: "완료",
    theyHearLabel: "상대방이 말했어요",
    youUnderstandLabel: "당신이 이해하는 것",
    literalLabel: "직역",
    tryAgainLabel: "다시 듣기",
    noSpeechSupportLabel: "이 브라우저에서는 음성 인식이 지원되지 않습니다. Chrome을 사용해 보세요.",
  },

  ko: {
    categoryLabels: { greetings: "인사 & 기본", food: "음식 & 식당", transport: "이동하기", shopping: "쇼핑 & 호텔", emergency: "긴급 & 건강" },
    phraseLabels: { "hello": "안녕하세요", "goodbye": "안녕히 가세요", "thank you": "감사합니다", "thank you very much": "정말 감사합니다", "please": "부탁합니다", "excuse me": "실례합니다", "sorry": "죄송합니다", "yes": "네", "no": "아니요", "you're welcome": "천만에요", "my name is...": "제 이름은…", "nice to meet you": "만나서 반갑습니다", "how are you?": "잘 지내세요?", "i'm fine, thank you": "잘 지냅니다, 감사합니다", "do you speak english?": "영어 하세요?", "i don't understand": "이해 못 했습니다", "can you speak slower?": "천천히 말씀해 주세요", "cheers!": "건배!", "good morning": "좋은 아침이에요", "good night": "안녕히 주무세요", "the bill please": "계산서 주세요", "no ice": "얼음 없이", "delicious": "맛있어요", "one more please": "하나 더 주세요", "water please": "물 주세요", "no spicy": "안 맵게 해주세요", "i am vegetarian": "저는 채식주의자예요", "i am allergic to peanuts": "땅콩 알레르기가 있어요", "no MSG please": "MSG 없이", "what do you recommend?": "뭘 추천하세요?", "a table for two": "2인 테이블", "the menu please": "메뉴 주세요", "do you have...": "…있나요?", "well done": "완전히 익혀서", "medium rare": "미디엄 레어로", "takeaway please": "포장해 주세요", "very delicious": "정말 맛있어요", "no meat": "고기 없이", "no dairy": "유제품 없이", "can i have the receipt?": "영수증 주세요", "where is the bathroom?": "화장실이 어디예요?", "how much is this?": "이거 얼마예요?", "how far is it?": "얼마나 멀어요?", "turn left": "왼쪽으로 도세요", "turn right": "오른쪽으로 도세요", "go straight": "직진하세요", "stop here": "여기 세워주세요", "take me to the airport": "공항으로 가주세요", "how much to the airport?": "공항까지 얼마예요?", "i want to go to...": "…에 가고 싶어요", "where is the train station?": "기차역이 어디예요?", "where is the bus stop?": "버스 정류장이 어디예요?", "i am lost": "길을 잃었어요", "can you call a taxi?": "택시 불러주세요", "wait here please": "여기서 기다려 주세요", "how long does it take?": "얼마나 걸려요?", "is it far?": "멀어요?", "on the left": "왼쪽에", "on the right": "오른쪽에", "straight ahead": "직진", "too expensive": "너무 비싸요", "do you have a discount?": "할인 있어요?", "i'll take it": "이걸로 할게요", "do you have this in another size?": "다른 사이즈 있어요?", "do you have this in another color?": "다른 색 있어요?", "can i try it on?": "입어봐도 돼요?", "receipt please": "영수증 주세요", "do you accept credit card?": "카드 되나요?", "i have a reservation": "예약이 있어요", "check in please": "체크인 해주세요", "check out please": "체크아웃 해주세요", "what time is check out?": "체크아웃이 몇 시예요?", "can i have a room?": "방 있어요?", "is breakfast included?": "아침 포함이에요?", "the wifi password please": "와이파이 비밀번호", "my room key please": "방 열쇠 주세요", "can you help me?": "도와주세요", "i want a refund": "환불해 주세요", "is there a pharmacy nearby?": "근처에 약국 있어요?", "help!": "도와주세요!", "call the police": "경찰 불러주세요", "call an ambulance": "구급차 불러주세요", "i need a doctor": "의사가 필요해요", "i am sick": "아파요", "i have a fever": "열이 있어요", "i have a stomach ache": "배가 아파요", "i am in pain": "아파요", "i am allergic to...": "…알레르기가 있어요", "where is the hospital?": "병원이 어디예요?", "where is the pharmacy?": "약국이 어디예요?", "i need medicine": "약이 필요해요", "please call this number": "이 번호로 전화해 주세요", "i have lost my passport": "여권을 잃어버렸어요", "i have been robbed": "도둑맞았어요", "i need help": "도움이 필요해요", "is there a doctor nearby?": "근처에 의사 있어요?", "this is an emergency": "긴급 상황이에요", "please hurry": "빨리 해주세요", "i don't feel well": "몸이 안 좋아요" },
    appTagline: "어떤 문장이든 말할 수 있어요. 읽기 불필요.",
    iSpeak: "내가 쓰는 언어",
    iWantToSpeak: "말하고 싶은 언어",
    placeholder: "한국어로 문장을 입력하세요...",
    sayItButton: "말해보기 →",
    hearSlowly: "천천히 듣기",
    naturalSpeed: "자연스러운 속도",
    playing: "재생 중...",
    stop: "정지",
    sayThisIn: "이 말을 하세요:",
    wordByWord: "단어별 분석",
    soundsLike: "이렇게 들려요",
    means: "뜻:",
    proTip: "팁",
    formalVersion: "격식체",
    backToList: "← 목록으로 돌아가기",
    quickPhrases: "자주 쓰는 표현 — 탭하면 바로 확인",
    customPhrasesNote: "직접 입력한 문장은 AI가 생성합니다",
    instant: "즉시",
    generating: "분석 중...",
    errorMessage: "오류가 발생했습니다. 다시 시도해 주세요.",
    toneLabels: {
      rising:  { label: "올라감",  desc: "끝에서 목소리가 올라감" },
      falling: { label: "내려감",  desc: "목소리가 내려감" },
      flat:    { label: "평탄",    desc: "목소리를 일정하게 유지" },
      dipping: { label: "내렸다 올라감", desc: "내려갔다가 다시 올라감" },
      high:    { label: "높음",    desc: "높게 시작하고 유지" },
      low:     { label: "낮음",    desc: "낮게 시작하고 유지" },
      broken:  { label: "끊김",    desc: "목이 조여지는 소리" },
    },
    listenLabel: "👂 听取对方回应",
    listeningLabel: "正在聆听 — 他们可以说话了",
    stopLabel: "完成",
    theyHearLabel: "他们说",
    youUnderstandLabel: "你理解",
    literalLabel: "字面意思",
    tryAgainLabel: "再次聆听",
    noSpeechSupportLabel: "此浏览器不支持语音识别，请使用Chrome浏览器。",
  },

  zh: {
    categoryLabels: { greetings: "问候和基础", food: "餐饮", transport: "出行", shopping: "购物和酒店", emergency: "紧急和健康" },
    phraseLabels: { "hello": "你好", "goodbye": "再见", "thank you": "谢谢", "thank you very much": "非常感谢", "please": "请", "excuse me": "打扰一下", "sorry": "对不起", "yes": "是", "no": "不", "you're welcome": "不客气", "my name is...": "我叫…", "nice to meet you": "很高兴认识你", "how are you?": "你好吗?", "i'm fine, thank you": "我很好，谢谢", "do you speak english?": "你会说英文吗?", "i don't understand": "我不明白", "can you speak slower?": "请说慢一点", "cheers!": "干杯!", "good morning": "早上好", "good night": "晚安", "the bill please": "买单", "no ice": "不要冰", "delicious": "好吃", "one more please": "再来一个", "water please": "请给我水", "no spicy": "不要辣", "i am vegetarian": "我吃素", "i am allergic to peanuts": "我对花生过敏", "no MSG please": "不要味精", "what do you recommend?": "你推荐什么?", "a table for two": "两人桌", "the menu please": "菜单", "do you have...": "有…吗?", "well done": "全熟", "medium rare": "三分熟", "takeaway please": "打包", "very delicious": "非常好吃", "no meat": "不要肉", "no dairy": "不要奶制品", "can i have the receipt?": "要收据", "where is the bathroom?": "厕所在哪里?", "how much is this?": "这个多少钱?", "how far is it?": "有多远?", "turn left": "左转", "turn right": "右转", "go straight": "直走", "stop here": "停在这里", "take me to the airport": "去机场", "how much to the airport?": "去机场多少钱?", "i want to go to...": "我想去…", "where is the train station?": "火车站在哪里?", "where is the bus stop?": "公交站在哪里?", "i am lost": "我迷路了", "can you call a taxi?": "帮我叫出租车", "wait here please": "请在这里等", "how long does it take?": "需要多长时间?", "is it far?": "远吗?", "on the left": "在左边", "on the right": "在右边", "straight ahead": "直走", "too expensive": "太贵了", "do you have a discount?": "有折扣吗?", "i'll take it": "我要这个", "do you have this in another size?": "有其他尺码吗?", "do you have this in another color?": "有其他颜色吗?", "can i try it on?": "可以试穿吗?", "receipt please": "收据", "do you accept credit card?": "可以刷卡吗?", "i have a reservation": "我有预订", "check in please": "办理入住", "check out please": "办理退房", "what time is check out?": "几点退房?", "can i have a room?": "有房间吗?", "is breakfast included?": "包含早餐吗?", "the wifi password please": "WiFi密码", "my room key please": "我的房卡", "can you help me?": "你能帮我吗?", "i want a refund": "我要退款", "is there a pharmacy nearby?": "附近有药店吗?", "help!": "救命!", "call the police": "叫警察", "call an ambulance": "叫救护车", "i need a doctor": "我需要医生", "i am sick": "我生病了", "i have a fever": "我发烧了", "i have a stomach ache": "我肚子疼", "i am in pain": "我很痛", "i am allergic to...": "我对…过敏", "where is the hospital?": "医院在哪里?", "where is the pharmacy?": "药店在哪里?", "i need medicine": "我需要药", "please call this number": "请打这个号码", "i have lost my passport": "我丢了护照", "i have been robbed": "我被抢了", "i need help": "我需要帮助", "is there a doctor nearby?": "附近有医生吗?", "this is an emergency": "这是紧急情况", "please hurry": "请快点", "i don't feel well": "我不舒服" },
    appTagline: "说任何短语，无需阅读。",
    iSpeak: "我说",
    iWantToSpeak: "我想说",
    placeholder: "用中文输入任何短语...",
    sayItButton: "说出来 →",
    hearSlowly: "慢速听",
    naturalSpeed: "正常速度",
    playing: "播放中...",
    stop: "停止",
    sayThisIn: "用这种语言说：",
    wordByWord: "逐词解析",
    soundsLike: "听起来像",
    means: "意思：",
    proTip: "小贴士",
    formalVersion: "正式说法",
    backToList: "← 返回列表",
    quickPhrases: "常用短语 — 点击即查",
    customPhrasesNote: "自定义短语由AI生成",
    instant: "即时",
    generating: "正在分析...",
    errorMessage: "出错了，请重试。",
    toneLabels: {
      rising:  { label: "上升",   desc: "声音在结尾上升" },
      falling: { label: "下降",   desc: "声音下降" },
      flat:    { label: "平",     desc: "保持声音平稳" },
      dipping: { label: "降升",   desc: "先降后升" },
      high:    { label: "高",     desc: "开始并保持高音" },
      low:     { label: "低",     desc: "开始并保持低音" },
      broken:  { label: "入声",   desc: "喉咙收紧，短促音" },
    },
    listenLabel: "👂 Ouvir a resposta deles",
    listeningLabel: "Ouvindo — eles podem falar agora",
    stopLabel: "Pronto",
    theyHearLabel: "Eles disseram",
    youUnderstandLabel: "Você entende",
    literalLabel: "Literalmente",
    tryAgainLabel: "Ouvir novamente",
    noSpeechSupportLabel: "Reconhecimento de voz não suportado. Tente o Chrome.",
  },

  pt: {
    categoryLabels: { greetings: "Saudações & Básico", food: "Comida & Restaurantes", transport: "Como se locomover", shopping: "Compras & Hotéis", emergency: "Emergência & Saúde" },
    phraseLabels: { "hello": "Olá", "goodbye": "Tchau", "thank you": "Obrigado/a", "thank you very much": "Muito obrigado/a", "please": "Por favor", "excuse me": "Com licença", "sorry": "Desculpe", "yes": "Sim", "no": "Não", "you're welcome": "De nada", "my name is...": "Meu nome é…", "nice to meet you": "Prazer em conhecer", "how are you?": "Como vai?", "i'm fine, thank you": "Bem, obrigado/a", "do you speak english?": "Fala inglês?", "i don't understand": "Não entendo", "can you speak slower?": "Pode falar mais devagar?", "cheers!": "Saúde!", "good morning": "Bom dia", "good night": "Boa noite", "the bill please": "A conta, por favor", "no ice": "Sem gelo", "delicious": "Delicioso", "one more please": "Mais um, por favor", "water please": "Água, por favor", "no spicy": "Sem pimenta", "i am vegetarian": "Sou vegetariano/a", "i am allergic to peanuts": "Sou alérgico a amendoim", "no MSG please": "Sem glutamato", "what do you recommend?": "O que você recomenda?", "a table for two": "Uma mesa para dois", "the menu please": "O cardápio, por favor", "do you have...": "Você tem…?", "well done": "Bem passado", "medium rare": "Mal passado", "takeaway please": "Para viagem", "very delicious": "Muito delicioso", "no meat": "Sem carne", "no dairy": "Sem laticínios", "can i have the receipt?": "O recibo, por favor", "where is the bathroom?": "Onde é o banheiro?", "how much is this?": "Quanto custa?", "how far is it?": "Qual a distância?", "turn left": "Vire à esquerda", "turn right": "Vire à direita", "go straight": "Siga em frente", "stop here": "Pare aqui", "take me to the airport": "Me leve ao aeroporto", "how much to the airport?": "Quanto ao aeroporto?", "i want to go to...": "Quero ir a…", "where is the train station?": "Onde é a estação?", "where is the bus stop?": "Onde é o ponto de ônibus?", "i am lost": "Estou perdido/a", "can you call a taxi?": "Pode chamar um táxi?", "wait here please": "Espere aqui", "how long does it take?": "Quanto tempo leva?", "is it far?": "É longe?", "on the left": "À esquerda", "on the right": "À direita", "straight ahead": "Em frente", "too expensive": "Muito caro", "do you have a discount?": "Tem desconto?", "i'll take it": "Vou levar", "do you have this in another size?": "Tem em outro tamanho?", "do you have this in another color?": "Tem em outra cor?", "can i try it on?": "Posso experimentar?", "receipt please": "O recibo", "do you accept credit card?": "Aceita cartão?", "i have a reservation": "Tenho uma reserva", "check in please": "Fazer check-in", "check out please": "Fazer check-out", "what time is check out?": "Que horas é o check-out?", "can i have a room?": "Tem quarto?", "is breakfast included?": "Café da manhã incluído?", "the wifi password please": "A senha do wifi", "my room key please": "Minha chave do quarto", "can you help me?": "Pode me ajudar?", "i want a refund": "Quero um reembolso", "is there a pharmacy nearby?": "Tem farmácia perto?", "help!": "Socorro!", "call the police": "Chame a polícia", "call an ambulance": "Chame uma ambulância", "i need a doctor": "Preciso de um médico", "i am sick": "Estou doente", "i have a fever": "Estou com febre", "i have a stomach ache": "Estou com dor de estômago", "i am in pain": "Estou com dor", "i am allergic to...": "Sou alérgico a…", "where is the hospital?": "Onde é o hospital?", "where is the pharmacy?": "Onde é a farmácia?", "i need medicine": "Preciso de remédio", "please call this number": "Ligue para este número", "i have lost my passport": "Perdi meu passaporte", "i have been robbed": "Fui assaltado/a", "i need help": "Preciso de ajuda", "is there a doctor nearby?": "Tem médico perto?", "this is an emergency": "É uma emergência", "please hurry": "Por favor, apresse-se", "i don't feel well": "Não estou bem" },
    appTagline: "Fale qualquer frase. Sem necessidade de ler.",
    iSpeak: "Eu falo",
    iWantToSpeak: "Quero falar",
    placeholder: "Digite qualquer frase em português...",
    sayItButton: "FALE →",
    hearSlowly: "Ouvir devagar",
    naturalSpeed: "Velocidade natural",
    playing: "Reproduzindo...",
    stop: "Parar",
    sayThisIn: "Diga isso em",
    wordByWord: "Análise palavra por palavra",
    soundsLike: "Soa como",
    means: "Significa:",
    proTip: "Dica",
    formalVersion: "Versão formal",
    backToList: "← Voltar à lista",
    quickPhrases: "Frases rápidas — toque para ver",
    customPhrasesNote: "Frases personalizadas são geradas por IA",
    instant: "instantâneo",
    generating: "Analisando para você...",
    errorMessage: "Algo deu errado. Por favor tente novamente.",
    toneLabels: {
      rising:  { label: "Subindo",   desc: "Voz SOBE no final" },
      falling: { label: "Descendo",  desc: "Voz DESCE" },
      flat:    { label: "Plano",     desc: "Manter voz NIVELADA" },
      dipping: { label: "Desce-sobe", desc: "Desce depois sobe" },
      high:    { label: "Alto",      desc: "Começar e manter ALTO" },
      low:     { label: "Baixo",     desc: "Começar e manter BAIXO" },
      broken:  { label: "Quebrado",  desc: "Garganta fechada, som cortado" },
    },
    listenLabel: "👂 Ascolta la loro risposta",
    listeningLabel: "Ascoltando — possono parlare ora",
    stopLabel: "Fatto",
    theyHearLabel: "Hanno detto",
    youUnderstandLabel: "Capisci",
    literalLabel: "Letteralmente",
    tryAgainLabel: "Ascolta ancora",
    noSpeechSupportLabel: "Riconoscimento vocale non supportato. Prova Chrome.",
  },

  it: {
    categoryLabels: { greetings: "Saluti e basi", food: "Cibo e ristoranti", transport: "Spostarsi", shopping: "Shopping e hotel", emergency: "Emergenze e salute" },
    phraseLabels: { "hello": "Ciao", "goodbye": "Arrivederci", "thank you": "Grazie", "thank you very much": "Grazie mille", "please": "Per favore", "excuse me": "Mi scusi", "sorry": "Mi dispiace", "yes": "Sì", "no": "No", "you're welcome": "Prego", "my name is...": "Mi chiamo…", "nice to meet you": "Piacere", "how are you?": "Come sta?", "i'm fine, thank you": "Bene, grazie", "do you speak english?": "Parla inglese?", "i don't understand": "Non capisco", "can you speak slower?": "Può parlare più lentamente?", "cheers!": "Cin cin!", "good morning": "Buongiorno", "good night": "Buonanotte", "the bill please": "Il conto, per favore", "no ice": "Senza ghiaccio", "delicious": "Delizioso", "one more please": "Ancora uno, per favore", "water please": "Acqua, per favore", "no spicy": "Non piccante", "i am vegetarian": "Sono vegetariano/a", "i am allergic to peanuts": "Sono allergico alle arachidi", "no MSG please": "Senza glutammato", "what do you recommend?": "Cosa consiglia?", "a table for two": "Un tavolo per due", "the menu please": "Il menu, per favore", "do you have...": "Ha…?", "well done": "Ben cotto", "medium rare": "Al sangue", "takeaway please": "Da portare via", "very delicious": "Buonissimo", "no meat": "Senza carne", "no dairy": "Senza latticini", "can i have the receipt?": "Lo scontrino, per favore", "where is the bathroom?": "Dov'è il bagno?", "how much is this?": "Quanto costa?", "how far is it?": "Quanto è lontano?", "turn left": "Giri a sinistra", "turn right": "Giri a destra", "go straight": "Vada dritto", "stop here": "Si fermi qui", "take me to the airport": "Mi porti all'aeroporto", "how much to the airport?": "Quanto all'aeroporto?", "i want to go to...": "Voglio andare a…", "where is the train station?": "Dov'è la stazione?", "where is the bus stop?": "Dov'è la fermata?", "i am lost": "Mi sono perso/a", "can you call a taxi?": "Può chiamare un taxi?", "wait here please": "Aspetti qui", "how long does it take?": "Quanto ci vuole?", "is it far?": "È lontano?", "on the left": "A sinistra", "on the right": "A destra", "straight ahead": "Dritto", "too expensive": "Troppo caro", "do you have a discount?": "C'è uno sconto?", "i'll take it": "Lo prendo", "do you have this in another size?": "Ce l'ha in un'altra taglia?", "do you have this in another color?": "Ce l'ha in un altro colore?", "can i try it on?": "Posso provarlo?", "receipt please": "Lo scontrino", "do you accept credit card?": "Accettate carte?", "i have a reservation": "Ho una prenotazione", "check in please": "Check-in", "check out please": "Check-out", "what time is check out?": "A che ora è il check-out?", "can i have a room?": "Avete una camera?", "is breakfast included?": "La colazione è inclusa?", "the wifi password please": "La password del wifi", "my room key please": "La chiave della mia camera", "can you help me?": "Può aiutarmi?", "i want a refund": "Voglio un rimborso", "is there a pharmacy nearby?": "C'è una farmacia?", "help!": "Aiuto!", "call the police": "Chiami la polizia", "call an ambulance": "Chiami un'ambulanza", "i need a doctor": "Ho bisogno di un medico", "i am sick": "Sono malato/a", "i have a fever": "Ho la febbre", "i have a stomach ache": "Ho mal di stomaco", "i am in pain": "Ho dolore", "i am allergic to...": "Sono allergico a…", "where is the hospital?": "Dov'è l'ospedale?", "where is the pharmacy?": "Dov'è la farmacia?", "i need medicine": "Ho bisogno di medicine", "please call this number": "Chiami questo numero", "i have lost my passport": "Ho perso il passaporto", "i have been robbed": "Sono stato derubato", "i need help": "Ho bisogno di aiuto", "is there a doctor nearby?": "C'è un medico?", "this is an emergency": "È un'emergenza", "please hurry": "Si affretti", "i don't feel well": "Non mi sento bene" },
    appTagline: "Di qualsiasi frase. Senza leggere.",
    iSpeak: "Parlo",
    iWantToSpeak: "Voglio parlare",
    placeholder: "Scrivi qualsiasi frase in italiano...",
    sayItButton: "DILLO →",
    hearSlowly: "Ascolta lentamente",
    naturalSpeed: "Velocità naturale",
    playing: "In riproduzione...",
    stop: "Ferma",
    sayThisIn: "Di' questo in",
    wordByWord: "Analisi parola per parola",
    soundsLike: "Suona come",
    means: "Significa:",
    proTip: "Consiglio",
    formalVersion: "Versione formale",
    backToList: "← Torna alla lista",
    quickPhrases: "Frasi rapide — tocca per vedere",
    customPhrasesNote: "Le frasi personalizzate sono generate dall'IA",
    instant: "immediato",
    generating: "Analizzando per te...",
    errorMessage: "Qualcosa è andato storto. Riprova.",
    toneLabels: {
      rising:  { label: "Ascendente",  desc: "Voce sale alla fine" },
      falling: { label: "Discendente", desc: "Voce scende" },
      flat:    { label: "Piatto",      desc: "Mantieni la voce LIVELLATA" },
      dipping: { label: "Scende-sale", desc: "Scende poi risale" },
      high:    { label: "Alto",        desc: "Inizia e rimani ALTO" },
      low:     { label: "Basso",       desc: "Inizia e rimani BASSO" },
      broken:  { label: "Spezzato",    desc: "Gola tesa, suono spezzato" },
    },
    listenLabel: "👂 استمع لردهم",
    listeningLabel: "جارٍ الاستماع — يمكنهم التحدث الآن",
    stopLabel: "تم",
    theyHearLabel: "قالوا",
    youUnderstandLabel: "أنت تفهم",
    literalLabel: "حرفياً",
    tryAgainLabel: "استمع مجدداً",
    noSpeechSupportLabel: "التعرف على الكلام غير مدعوم. جرب متصفح Chrome.",
  },

  ar: {
    categoryLabels: { greetings: "التحيات والأساسيات", food: "الطعام والمطاعم", transport: "التنقل", shopping: "التسوق والفنادق", emergency: "الطوارئ والصحة" },
    phraseLabels: { "hello": "مرحبا", "goodbye": "مع السلامة", "thank you": "شكراً", "thank you very much": "شكراً جزيلاً", "please": "من فضلك", "excuse me": "عفواً", "sorry": "آسف", "yes": "نعم", "no": "لا", "you're welcome": "عفواً", "my name is...": "اسمي…", "nice to meet you": "تشرفت بمعرفتك", "how are you?": "كيف حالك؟", "i'm fine, thank you": "بخير، شكراً", "do you speak english?": "هل تتحدث الإنجليزية؟", "i don't understand": "لا أفهم", "can you speak slower?": "هل يمكنك التحدث ببطء؟", "cheers!": "في صحتك!", "good morning": "صباح الخير", "good night": "تصبح على خير", "the bill please": "الحساب من فضلك", "no ice": "بدون ثلج", "delicious": "لذيذ", "one more please": "واحد آخر من فضلك", "water please": "ماء من فضلك", "no spicy": "بدون حار", "i am vegetarian": "أنا نباتي", "i am allergic to peanuts": "أنا حساس للفول السوداني", "no MSG please": "بدون غلوتامات", "what do you recommend?": "ماذا توصي؟", "a table for two": "طاولة لشخصين", "the menu please": "القائمة من فضلك", "do you have...": "هل عندك…؟", "well done": "مطبوخ جيداً", "medium rare": "نصف مطبوخ", "takeaway please": "للأخذ", "very delicious": "لذيذ جداً", "no meat": "بدون لحم", "no dairy": "بدون منتجات الألبان", "can i have the receipt?": "الفاتورة من فضلك", "where is the bathroom?": "أين الحمام؟", "how much is this?": "بكم هذا؟", "how far is it?": "كم المسافة؟", "turn left": "اتجه يساراً", "turn right": "اتجه يميناً", "go straight": "اذهب مباشرة", "stop here": "قف هنا", "take me to the airport": "خذني إلى المطار", "how much to the airport?": "كم تكلفة المطار؟", "i want to go to...": "أريد الذهاب إلى…", "where is the train station?": "أين محطة القطار؟", "where is the bus stop?": "أين موقف الحافلة؟", "i am lost": "أنا تائه", "can you call a taxi?": "هل يمكنك استدعاء تاكسي؟", "wait here please": "انتظر هنا", "how long does it take?": "كم يستغرق؟", "is it far?": "هل هو بعيد؟", "on the left": "على اليسار", "on the right": "على اليمين", "straight ahead": "مباشرة", "too expensive": "غالي جداً", "do you have a discount?": "هل هناك خصم؟", "i'll take it": "سآخذه", "do you have this in another size?": "هل عندك بمقاس آخر؟", "do you have this in another color?": "هل عندك بلون آخر؟", "can i try it on?": "هل يمكنني تجربته؟", "receipt please": "الإيصال من فضلك", "do you accept credit card?": "هل تقبل البطاقة؟", "i have a reservation": "عندي حجز", "check in please": "تسجيل الدخول", "check out please": "تسجيل الخروج", "what time is check out?": "متى موعد المغادرة؟", "can i have a room?": "هل يوجد غرفة؟", "is breakfast included?": "هل الفطور مشمول؟", "the wifi password please": "كلمة مرور الواي فاي", "my room key please": "مفتاح غرفتي", "can you help me?": "هل يمكنك مساعدتي؟", "i want a refund": "أريد استرداد المبلغ", "is there a pharmacy nearby?": "هل يوجد صيدلية قريبة؟", "help!": "النجدة!", "call the police": "اتصل بالشرطة", "call an ambulance": "اتصل بالإسعاف", "i need a doctor": "أحتاج طبيباً", "i am sick": "أنا مريض", "i have a fever": "عندي حمى", "i have a stomach ache": "عندي ألم في المعدة", "i am in pain": "أنا في ألم", "i am allergic to...": "أنا حساس لـ…", "where is the hospital?": "أين المستشفى؟", "where is the pharmacy?": "أين الصيدلية؟", "i need medicine": "أحتاج دواءً", "please call this number": "اتصل بهذا الرقم", "i have lost my passport": "فقدت جواز سفري", "i have been robbed": "تعرضت للسرقة", "i need help": "أحتاج مساعدة", "is there a doctor nearby?": "هل يوجد طبيب قريب؟", "this is an emergency": "هذه حالة طوارئ", "please hurry": "أسرع من فضلك", "i don't feel well": "لا أشعر بتحسن" },
    appTagline: "قل أي جملة. لا حاجة للقراءة.",
    iSpeak: "أتحدث",
    iWantToSpeak: "أريد أن أتحدث",
    placeholder: "اكتب أي جملة بالعربية...",
    sayItButton: "قلها ←",
    hearSlowly: "استمع ببطء",
    naturalSpeed: "السرعة الطبيعية",
    playing: "يُشغَّل...",
    stop: "إيقاف",
    sayThisIn: "قل هذا بـ",
    wordByWord: "تحليل كلمة بكلمة",
    soundsLike: "يشبه",
    means: "يعني:",
    proTip: "نصيحة",
    formalVersion: "النسخة الرسمية",
    backToList: "← العودة إلى القائمة",
    quickPhrases: "عبارات سريعة — اضغط للتحليل الفوري",
    customPhrasesNote: "العبارات المخصصة تُنشأ بالذكاء الاصطناعي",
    instant: "فوري",
    generating: "جارٍ التحليل...",
    errorMessage: "حدث خطأ. يرجى المحاولة مجدداً.",
    toneLabels: {
      rising:  { label: "صاعد",    desc: "الصوت يرتفع في النهاية" },
      falling: { label: "هابط",    desc: "الصوت يهبط" },
      flat:    { label: "مستوٍ",   desc: "الحفاظ على الصوت ثابتاً" },
      dipping: { label: "ينخفض ثم يرتفع", desc: "ينخفض ثم يعود للارتفاع" },
      high:    { label: "مرتفع",   desc: "يبدأ ويبقى مرتفعاً" },
      low:     { label: "منخفض",   desc: "يبدأ ويبقى منخفضاً" },
      broken:  { label: "مكسور",   desc: "صوت متقطع من الحلق" },
    },
    listenLabel: "👂 उनका जवाब सुनें",
    listeningLabel: "सुन रहे हैं — वे अब बोल सकते हैं",
    stopLabel: "हो गया",
    theyHearLabel: "उन्होंने कहा",
    youUnderstandLabel: "आप समझते हैं",
    literalLabel: "शाब्दिक अर्थ",
    tryAgainLabel: "फिर से सुनें",
    noSpeechSupportLabel: "इस ब्राउज़र में वाक् पहचान समर्थित नहीं है। Chrome आज़माएं।",
  },

  hi: {
    categoryLabels: { greetings: "अभिवादन और मूल बातें", food: "खाना-पीना", transport: "आवागमन", shopping: "खरीदारी और होटल", emergency: "आपातकाल और स्वास्थ्य" },
    phraseLabels: { "hello": "नमस्ते", "goodbye": "अलविदा", "thank you": "धन्यवाद", "thank you very much": "बहुत धन्यवाद", "please": "कृपया", "excuse me": "माफ करें", "sorry": "माफी", "yes": "हाँ", "no": "नहीं", "you're welcome": "आपका स्वागत है", "my name is...": "मेरा नाम… है", "nice to meet you": "मिलकर खुशी हुई", "how are you?": "आप कैसे हैं?", "i'm fine, thank you": "मैं ठीक हूँ, धन्यवाद", "do you speak english?": "क्या आप अंग्रेजी बोलते हैं?", "i don't understand": "मुझे समझ नहीं आया", "can you speak slower?": "कृपया धीरे बोलें", "cheers!": "चीयर्स!", "good morning": "सुप्रभात", "good night": "शुभ रात्रि", "the bill please": "बिल लाइए", "no ice": "बर्फ नहीं", "delicious": "स्वादिष्ट", "one more please": "एक और", "water please": "पानी दीजिए", "no spicy": "मसालेदार नहीं", "i am vegetarian": "मैं शाकाहारी हूँ", "i am allergic to peanuts": "मुझे मूंगफली से एलर्जी है", "no MSG please": "अजीनोमोटो नहीं", "what do you recommend?": "आप क्या सुझाएंगे?", "a table for two": "दो लोगों के लिए मेज", "the menu please": "मेनू दिखाइए", "do you have...": "क्या आपके पास… है?", "well done": "अच्छे से पकाएं", "medium rare": "हल्का कच्चा", "takeaway please": "पैक करके दीजिए", "very delicious": "बहुत स्वादिष्ट", "no meat": "मांस नहीं", "no dairy": "दूध उत्पाद नहीं", "can i have the receipt?": "रसीद दीजिए", "where is the bathroom?": "शौचालय कहाँ है?", "how much is this?": "यह कितने का है?", "how far is it?": "कितनी दूर है?", "turn left": "बाएं मुड़ें", "turn right": "दाएं मुड़ें", "go straight": "सीधे जाएं", "stop here": "यहाँ रोकें", "take me to the airport": "हवाई अड्डे पर ले चलें", "how much to the airport?": "हवाई अड्डे तक कितना?", "i want to go to...": "मुझे… जाना है", "where is the train station?": "रेलवे स्टेशन कहाँ है?", "where is the bus stop?": "बस स्टॉप कहाँ है?", "i am lost": "मैं खो गया/गई हूँ", "can you call a taxi?": "टैक्सी बुला सकते हैं?", "wait here please": "यहाँ रुकें", "how long does it take?": "कितना समय लगेगा?", "is it far?": "दूर है?", "on the left": "बाईं ओर", "on the right": "दाईं ओर", "straight ahead": "सीधे", "too expensive": "बहुत महंगा", "do you have a discount?": "छूट मिलेगी?", "i'll take it": "मैं यह लूंगा", "do you have this in another size?": "दूसरे साइज में है?", "do you have this in another color?": "दूसरे रंग में है?", "can i try it on?": "पहन कर देख सकता हूँ?", "receipt please": "रसीद दीजिए", "do you accept credit card?": "क्रेडिट कार्ड चलेगा?", "i have a reservation": "मेरी बुकिंग है", "check in please": "चेक-इन करना है", "check out please": "चेक-आउट करना है", "what time is check out?": "चेक-आउट कब है?", "can i have a room?": "कमरा मिलेगा?", "is breakfast included?": "नाश्ता शामिल है?", "the wifi password please": "वाई-फाई पासवर्ड", "my room key please": "कमरे की चाबी", "can you help me?": "क्या आप मदद करेंगे?", "i want a refund": "मुझे रिफंड चाहिए", "is there a pharmacy nearby?": "पास में दवाई की दुकान है?", "help!": "बचाओ!", "call the police": "पुलिस बुलाओ", "call an ambulance": "एम्बुलेंस बुलाओ", "i need a doctor": "मुझे डॉक्टर चाहिए", "i am sick": "मैं बीमार हूँ", "i have a fever": "मुझे बुखार है", "i have a stomach ache": "पेट दर्द है", "i am in pain": "दर्द हो रहा है", "i am allergic to...": "मुझे… से एलर्जी है", "where is the hospital?": "अस्पताल कहाँ है?", "where is the pharmacy?": "दवाखाना कहाँ है?", "i need medicine": "दवाई चाहिए", "please call this number": "यह नंबर लगाइए", "i have lost my passport": "मेरा पासपोर्ट खो गया", "i have been robbed": "मेरा सामान चोरी हुआ", "i need help": "मुझे मदद चाहिए", "is there a doctor nearby?": "पास में डॉक्टर है?", "this is an emergency": "यह आपातकाल है", "please hurry": "जल्दी करें", "i don't feel well": "तबीयत ठीक नहीं" },
    appTagline: "कोई भी वाक्य बोलें। पढ़ने की जरूरत नहीं।",
    iSpeak: "मैं बोलता/बोलती हूँ",
    iWantToSpeak: "मैं बोलना चाहता/चाहती हूँ",
    placeholder: "हिंदी में कोई भी वाक्य लिखें...",
    sayItButton: "बोलो →",
    hearSlowly: "धीरे सुनें",
    naturalSpeed: "सामान्य गति",
    playing: "चल रहा है...",
    stop: "रोकें",
    sayThisIn: "यह इस भाषा में कहें:",
    wordByWord: "शब्द-दर-शब्द विश्लेषण",
    soundsLike: "सुनाई देता है",
    means: "मतलब:",
    proTip: "सुझाव",
    formalVersion: "औपचारिक संस्करण",
    backToList: "← सूची पर वापस जाएं",
    quickPhrases: "त्वरित वाक्य — तुरंत देखने के लिए टैप करें",
    customPhrasesNote: "कस्टम वाक्य AI द्वारा बनाए जाते हैं",
    instant: "तुरंत",
    generating: "विश्लेषण हो रहा है...",
    errorMessage: "कुछ गलत हुआ। कृपया पुनः प्रयास करें।",
    toneLabels: {
      rising:  { label: "ऊपर जाता",  desc: "आवाज़ अंत में ऊपर जाती है" },
      falling: { label: "नीचे जाता", desc: "आवाज़ नीचे जाती है" },
      flat:    { label: "सपाट",      desc: "आवाज़ स्थिर रखें" },
      dipping: { label: "नीचे फिर ऊपर", desc: "नीचे जाकर वापस ऊपर आती है" },
      high:    { label: "ऊंचा",      desc: "ऊंचा शुरू करें और रखें" },
      low:     { label: "नीचा",      desc: "नीचा शुरू करें और रखें" },
      broken:  { label: "टूटा",      desc: "गले से दबा हुआ स्वर" },
    },
    listenLabel: "👂 Слухати відповідь",
    listeningLabel: "Слухаю — вони можуть говорити",
    stopLabel: "Готово",
    theyHearLabel: "Вони сказали",
    youUnderstandLabel: "Ви розумієте",
    literalLabel: "Дослівно",
    tryAgainLabel: "Слухати знову",
    noSpeechSupportLabel: "Розпізнавання мовлення не підтримується. Спробуйте Chrome.",
  },

  uk: {
    categoryLabels: { greetings: "Привітання та основи", food: "Їжа та ресторани", transport: "Пересування", shopping: "Покупки та готелі", emergency: "Надзвичайні ситуації та здоров'я" },
    phraseLabels: { "hello": "Привіт", "goodbye": "До побачення", "thank you": "Дякую", "thank you very much": "Дуже дякую", "please": "Будь ласка", "excuse me": "Вибачте", "sorry": "Вибачте", "yes": "Так", "no": "Ні", "you're welcome": "Будь ласка", "my name is...": "Мене звати…", "nice to meet you": "Приємно познайомитися", "how are you?": "Як справи?", "i'm fine, thank you": "Добре, дякую", "do you speak english?": "Ви говорите англійською?", "i don't understand": "Я не розумію", "can you speak slower?": "Говоріть повільніше", "cheers!": "Будьмо!", "good morning": "Доброго ранку", "good night": "На добраніч", "the bill please": "Рахунок, будь ласка", "no ice": "Без льоду", "delicious": "Смачно", "one more please": "Ще один", "water please": "Воду, будь ласка", "no spicy": "Не гостре", "i am vegetarian": "Я вегетаріанець", "i am allergic to peanuts": "У мене алергія на арахіс", "no MSG please": "Без підсилювачів смаку", "what do you recommend?": "Що ви рекомендуєте?", "a table for two": "Столик на двох", "the menu please": "Меню, будь ласка", "do you have...": "У вас є…?", "well done": "Добре просмажене", "medium rare": "З кров'ю", "takeaway please": "З собою", "very delicious": "Дуже смачно", "no meat": "Без м'яса", "no dairy": "Без молочного", "can i have the receipt?": "Чек, будь ласка", "where is the bathroom?": "Де туалет?", "how much is this?": "Скільки це коштує?", "how far is it?": "Як далеко?", "turn left": "Ліворуч", "turn right": "Праворуч", "go straight": "Прямо", "stop here": "Зупиніться тут", "take me to the airport": "До аеропорту", "how much to the airport?": "Скільки до аеропорту?", "i want to go to...": "Мені треба до…", "where is the train station?": "Де вокзал?", "where is the bus stop?": "Де автобусна зупинка?", "i am lost": "Я заблукав/заблукала", "can you call a taxi?": "Викличте таксі", "wait here please": "Зачекайте тут", "how long does it take?": "Скільки часу займе?", "is it far?": "Далеко?", "on the left": "Ліворуч", "on the right": "Праворуч", "straight ahead": "Прямо", "too expensive": "Занадто дорого", "do you have a discount?": "Є знижка?", "i'll take it": "Я беру", "do you have this in another size?": "Є інший розмір?", "do you have this in another color?": "Є інший колір?", "can i try it on?": "Можна приміряти?", "receipt please": "Чек, будь ласка", "do you accept credit card?": "Чи приймаєте картку?", "i have a reservation": "У мене є бронювання", "check in please": "Заселення", "check out please": "Виселення", "what time is check out?": "О котрій виселення?", "can i have a room?": "Є кімнати?", "is breakfast included?": "Сніданок включений?", "the wifi password please": "Пароль від wifi", "my room key please": "Ключ від кімнати", "can you help me?": "Допоможіть мені", "i want a refund": "Хочу повернення коштів", "is there a pharmacy nearby?": "Є аптека поруч?", "help!": "Допоможіть!", "call the police": "Викличте поліцію", "call an ambulance": "Викличте швидку", "i need a doctor": "Мені потрібен лікар", "i am sick": "Я хворий/хвора", "i have a fever": "У мене температура", "i have a stomach ache": "У мене болить живіт", "i am in pain": "Мені боляче", "i am allergic to...": "У мене алергія на…", "where is the hospital?": "Де лікарня?", "where is the pharmacy?": "Де аптека?", "i need medicine": "Мені потрібні ліки", "please call this number": "Зателефонуйте за цим номером", "i have lost my passport": "Я загубив/загубила паспорт", "i have been robbed": "Мене пограбували", "i need help": "Мені потрібна допомога", "is there a doctor nearby?": "Є лікар поруч?", "this is an emergency": "Це надзвичайна ситуація", "please hurry": "Поспішіть", "i don't feel well": "Мені погано" },
    appTagline: "Говоріть будь-яку фразу. Читання не потрібне.",
    iSpeak: "Я розмовляю",
    iWantToSpeak: "Я хочу говорити",
    placeholder: "Введіть будь-яку фразу українською...",
    sayItButton: "СКАЖИ →",
    hearSlowly: "Слухати повільно",
    naturalSpeed: "Природна швидкість",
    playing: "Відтворення...",
    stop: "Зупинити",
    sayThisIn: "Скажіть це мовою",
    wordByWord: "Розбір слово за словом",
    soundsLike: "Звучить як",
    means: "Означає:",
    proTip: "Порада",
    formalVersion: "Офіційна версія",
    backToList: "← Назад до списку",
    quickPhrases: "Швидкі фрази — натисніть для миттєвого розбору",
    customPhrasesNote: "Власні фрази генеруються ШІ",
    instant: "миттєво",
    generating: "Аналіз...",
    errorMessage: "Щось пішло не так. Будь ласка, спробуйте ще раз.",
    toneLabels: {
      rising:  { label: "Висхідний",  desc: "Голос йде ВГОРУ наприкінці" },
      falling: { label: "Низхідний",  desc: "Голос йде ВНИЗ" },
      flat:    { label: "Рівний",     desc: "Тримайте голос РІВНО" },
      dipping: { label: "Спуск-підйом", desc: "Вниз потім назад вгору" },
      high:    { label: "Високий",    desc: "Починати і тримати ВИСОКО" },
      low:     { label: "Низький",    desc: "Починати і тримати НИЗЬКО" },
      broken:  { label: "Переривчастий", desc: "Напружене горло, уривчастий звук" },
    },
    listenLabel: "👂 Слушать ответ",
    listeningLabel: "Слушаю — они могут говорить",
    stopLabel: "Готово",
    theyHearLabel: "Они сказали",
    youUnderstandLabel: "Вы понимаете",
    literalLabel: "Дословно",
    tryAgainLabel: "Слушать снова",
    noSpeechSupportLabel: "Распознавание речи не поддерживается. Попробуйте Chrome.",
  },

  ru: {
    categoryLabels: { greetings: "Приветствия и основы", food: "Еда и рестораны", transport: "Передвижение", shopping: "Покупки и отели", emergency: "Экстренные ситуации и здоровье" },
    phraseLabels: { "hello": "Привет", "goodbye": "До свидания", "thank you": "Спасибо", "thank you very much": "Большое спасибо", "please": "Пожалуйста", "excuse me": "Извините", "sorry": "Извините", "yes": "Да", "no": "Нет", "you're welcome": "Пожалуйста", "my name is...": "Меня зовут…", "nice to meet you": "Приятно познакомиться", "how are you?": "Как дела?", "i'm fine, thank you": "Хорошо, спасибо", "do you speak english?": "Вы говорите по-английски?", "i don't understand": "Я не понимаю", "can you speak slower?": "Говорите медленнее", "cheers!": "За здоровье!", "good morning": "Доброе утро", "good night": "Спокойной ночи", "the bill please": "Счёт, пожалуйста", "no ice": "Без льда", "delicious": "Вкусно", "one more please": "Ещё один", "water please": "Воды, пожалуйста", "no spicy": "Не острое", "i am vegetarian": "Я вегетарианец", "i am allergic to peanuts": "У меня аллергия на арахис", "no MSG please": "Без усилителей вкуса", "what do you recommend?": "Что вы рекомендуете?", "a table for two": "Столик на двоих", "the menu please": "Меню, пожалуйста", "do you have...": "У вас есть…?", "well done": "Хорошо прожаренное", "medium rare": "С кровью", "takeaway please": "С собой", "very delicious": "Очень вкусно", "no meat": "Без мяса", "no dairy": "Без молочного", "can i have the receipt?": "Чек, пожалуйста", "where is the bathroom?": "Где туалет?", "how much is this?": "Сколько стоит?", "how far is it?": "Как далеко?", "turn left": "Налево", "turn right": "Направо", "go straight": "Прямо", "stop here": "Остановите здесь", "take me to the airport": "В аэропорт", "how much to the airport?": "Сколько до аэропорта?", "i want to go to...": "Мне нужно в…", "where is the train station?": "Где вокзал?", "where is the bus stop?": "Где автобусная остановка?", "i am lost": "Я заблудился/заблудилась", "can you call a taxi?": "Вызовите такси", "wait here please": "Подождите здесь", "how long does it take?": "Сколько времени займёт?", "is it far?": "Далеко?", "on the left": "Слева", "on the right": "Справа", "straight ahead": "Прямо", "too expensive": "Слишком дорого", "do you have a discount?": "Есть скидка?", "i'll take it": "Я беру", "do you have this in another size?": "Есть другой размер?", "do you have this in another color?": "Есть другой цвет?", "can i try it on?": "Можно примерить?", "receipt please": "Чек, пожалуйста", "do you accept credit card?": "Принимаете карту?", "i have a reservation": "У меня есть бронь", "check in please": "Заселение", "check out please": "Выселение", "what time is check out?": "Во сколько выселение?", "can i have a room?": "Есть номера?", "is breakfast included?": "Завтрак включён?", "the wifi password please": "Пароль от wifi", "my room key please": "Ключ от номера", "can you help me?": "Помогите мне", "i want a refund": "Хочу возврат", "is there a pharmacy nearby?": "Есть аптека рядом?", "help!": "Помогите!", "call the police": "Вызовите полицию", "call an ambulance": "Вызовите скорую", "i need a doctor": "Мне нужен врач", "i am sick": "Я болен/больна", "i have a fever": "У меня температура", "i have a stomach ache": "У меня болит живот", "i am in pain": "Мне больно", "i am allergic to...": "У меня аллергия на…", "where is the hospital?": "Где больница?", "where is the pharmacy?": "Где аптека?", "i need medicine": "Мне нужно лекарство", "please call this number": "Позвоните по этому номеру", "i have lost my passport": "Я потерял/потеряла паспорт", "i have been robbed": "Меня ограбили", "i need help": "Мне нужна помощь", "is there a doctor nearby?": "Есть врач рядом?", "this is an emergency": "Это чрезвычайная ситуация", "please hurry": "Поспешите", "i don't feel well": "Мне нехорошо" },
    appTagline: "Говорите любую фразу. Читать не нужно.",
    iSpeak: "Я говорю",
    iWantToSpeak: "Я хочу говорить",
    placeholder: "Введите любую фразу на русском...",
    sayItButton: "СКАЖИ →",
    hearSlowly: "Слушать медленно",
    naturalSpeed: "Естественная скорость",
    playing: "Воспроизведение...",
    stop: "Остановить",
    sayThisIn: "Скажите это на",
    wordByWord: "Разбор слово за словом",
    soundsLike: "Звучит как",
    means: "Означает:",
    proTip: "Совет",
    formalVersion: "Формальная версия",
    backToList: "← Назад к списку",
    quickPhrases: "Быстрые фразы — нажмите для мгновенного разбора",
    customPhrasesNote: "Фразы генерируются ИИ",
    instant: "мгновенно",
    generating: "Анализ...",
    errorMessage: "Что-то пошло не так. Пожалуйста, попробуйте ещё раз.",
    toneLabels: {
      rising:  { label: "Восходящий",  desc: "Голос идёт ВВЕРХ в конце" },
      falling: { label: "Нисходящий", desc: "Голос идёт ВНИЗ" },
      flat:    { label: "Ровный",      desc: "Держите голос РОВНО" },
      dipping: { label: "Спуск-подъём", desc: "Вниз затем вверх" },
      high:    { label: "Высокий",     desc: "Начинать и держать ВЫСОКО" },
      low:     { label: "Низкий",      desc: "Начинать и держать НИЗКО" },
      broken:  { label: "Прерывистый", desc: "Напряжённое горло, резкий звук" },
    },
    listenLabel: "👂 ฟังคำตอบของพวกเขา",
    listeningLabel: "กำลังฟัง — พวกเขาพูดได้เลย",
    stopLabel: "เสร็จแล้ว",
    theyHearLabel: "พวกเขาพูดว่า",
    youUnderstandLabel: "คุณเข้าใจ",
    literalLabel: "แปลตรงๆ",
    tryAgainLabel: "ฟังอีกครั้ง",
    noSpeechSupportLabel: "เบราว์เซอร์นี้ไม่รองรับการรู้จำเสียง ลอง Chrome ดู",
  },

  th: {
    categoryLabels: { greetings: "คำทักทายและพื้นฐาน", food: "อาหารและร้านอาหาร", transport: "การเดินทาง", shopping: "ช้อปปิ้งและโรงแรม", emergency: "ฉุกเฉินและสุขภาพ" },
    phraseLabels: { "hello": "สวัสดี", "goodbye": "ลาก่อน", "thank you": "ขอบคุณ", "thank you very much": "ขอบคุณมาก", "please": "กรุณา", "excuse me": "ขอโทษ", "sorry": "ขอโทษ", "yes": "ใช่", "no": "ไม่", "you're welcome": "ยินดี", "my name is...": "ผม/ฉันชื่อ…", "nice to meet you": "ยินดีที่ได้รู้จัก", "how are you?": "สบายดีไหม?", "i'm fine, thank you": "สบายดี ขอบคุณ", "do you speak english?": "คุณพูดภาษาอังกฤษได้ไหม?", "i don't understand": "ไม่เข้าใจ", "can you speak slower?": "พูดช้าๆ ได้ไหม?", "cheers!": "ชนแก้ว!", "good morning": "อรุณสวัสดิ์", "good night": "ราตรีสวัสดิ์", "the bill please": "เก็บเงินด้วย", "no ice": "ไม่ใส่น้ำแข็ง", "delicious": "อร่อย", "one more please": "อีกอันหนึ่ง", "water please": "น้ำเปล่า", "no spicy": "ไม่เผ็ด", "i am vegetarian": "ฉันกินเจ", "i am allergic to peanuts": "แพ้ถั่วลิสง", "no MSG please": "ไม่ใส่ผงชูรส", "what do you recommend?": "แนะนำอะไรดี?", "a table for two": "โต๊ะสองคน", "the menu please": "เมนูหน่อย", "do you have...": "มี… ไหม?", "well done": "สุกมากๆ", "medium rare": "กึ่งสุก", "takeaway please": "ห่อกลับบ้าน", "very delicious": "อร่อยมาก", "no meat": "ไม่ใส่เนื้อ", "no dairy": "ไม่ใส่นม", "can i have the receipt?": "ขอใบเสร็จ", "where is the bathroom?": "ห้องน้ำอยู่ที่ไหน?", "how much is this?": "อันนี้ราคาเท่าไหร่?", "how far is it?": "ไกลแค่ไหน?", "turn left": "เลี้ยวซ้าย", "turn right": "เลี้ยวขวา", "go straight": "ตรงไป", "stop here": "จอดตรงนี้", "take me to the airport": "พาไปสนามบิน", "how much to the airport?": "ไปสนามบินเท่าไหร่?", "i want to go to...": "อยากไป…", "where is the train station?": "สถานีรถไฟอยู่ที่ไหน?", "where is the bus stop?": "ป้ายรถเมล์อยู่ที่ไหน?", "i am lost": "ฉันหลงทาง", "can you call a taxi?": "เรียกแท็กซี่ให้หน่อยได้ไหม?", "wait here please": "รอที่นี่", "how long does it take?": "ใช้เวลานานแค่ไหน?", "is it far?": "ไกลไหม?", "on the left": "ทางซ้าย", "on the right": "ทางขวา", "straight ahead": "ตรงไปข้างหน้า", "too expensive": "แพงเกินไป", "do you have a discount?": "มีส่วนลดไหม?", "i'll take it": "เอาอันนี้", "do you have this in another size?": "มีไซส์อื่นไหม?", "do you have this in another color?": "มีสีอื่นไหม?", "can i try it on?": "ลองได้ไหม?", "receipt please": "ใบเสร็จ", "do you accept credit card?": "รับบัตรเครดิตไหม?", "i have a reservation": "มีจอง", "check in please": "เช็คอิน", "check out please": "เช็คเอาท์", "what time is check out?": "เช็คเอาท์กี่โมง?", "can i have a room?": "มีห้องว่างไหม?", "is breakfast included?": "รวมอาหารเช้าไหม?", "the wifi password please": "รหัส wifi", "my room key please": "กุญแจห้อง", "can you help me?": "ช่วยฉันได้ไหม?", "i want a refund": "ขอคืนเงิน", "is there a pharmacy nearby?": "มีร้านขายยาใกล้ๆ ไหม?", "help!": "ช่วยด้วย!", "call the police": "โทรแจ้งตำรวจ", "call an ambulance": "โทรเรียกรถพยาบาล", "i need a doctor": "ต้องการหมอ", "i am sick": "ฉันป่วย", "i have a fever": "มีไข้", "i have a stomach ache": "ปวดท้อง", "i am in pain": "เจ็บปวด", "i am allergic to...": "แพ้…", "where is the hospital?": "โรงพยาบาลอยู่ที่ไหน?", "where is the pharmacy?": "ร้านขายยาอยู่ที่ไหน?", "i need medicine": "ต้องการยา", "please call this number": "โทรหาเบอร์นี้", "i have lost my passport": "ทำพาสปอร์ตหาย", "i have been robbed": "ถูกปล้น", "i need help": "ต้องการความช่วยเหลือ", "is there a doctor nearby?": "มีหมออยู่ใกล้ๆ ไหม?", "this is an emergency": "นี่เป็นเหตุฉุกเฉิน", "please hurry": "รีบด้วย", "i don't feel well": "ไม่สบาย" },
    appTagline: "พูดประโยคไหนก็ได้ ไม่ต้องอ่าน",
    iSpeak: "ฉันพูด",
    iWantToSpeak: "ฉันอยากพูด",
    placeholder: "พิมพ์ประโยคใดก็ได้เป็นภาษาไทย...",
    sayItButton: "พูดเลย →",
    hearSlowly: "ฟังช้าๆ",
    naturalSpeed: "ความเร็วปกติ",
    playing: "กำลังเล่น...",
    stop: "หยุด",
    sayThisIn: "พูดสิ่งนี้เป็น",
    wordByWord: "วิเคราะห์ทีละคำ",
    soundsLike: "ฟังดูเหมือน",
    means: "หมายความว่า:",
    proTip: "เคล็ดลับ",
    formalVersion: "รูปแบบทางการ",
    backToList: "← กลับสู่รายการ",
    quickPhrases: "ประโยคด่วน — แตะเพื่อดูทันที",
    customPhrasesNote: "ประโยคที่พิมพ์เองสร้างโดย AI",
    instant: "ทันที",
    generating: "กำลังวิเคราะห์...",
    errorMessage: "เกิดข้อผิดพลาด กรุณาลองใหม่",
    toneLabels: {
      rising:  { label: "ขึ้น",      desc: "เสียงขึ้นตอนท้าย" },
      falling: { label: "ลง",       desc: "เสียงลดลง" },
      flat:    { label: "เรียบ",    desc: "รักษาเสียงให้คงที่" },
      dipping: { label: "ลงแล้วขึ้น", desc: "ลงแล้วกลับขึ้น" },
      high:    { label: "สูง",      desc: "เริ่มและคงไว้สูง" },
      low:     { label: "ต่ำ",      desc: "เริ่มและคงไว้ต่ำ" },
      broken:  { label: "ตก",      desc: "เสียงตึงในลำคอ" },
    },
  },
};

export default UI_TEXT;
